/* tslint:disable */
/* eslint-disable */
/**
 * ConnectHub API
 * Unified integration, token, and proxy layer for Clancy Digital-Employees
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { OwnershipScope } from './OwnershipScope.js';
import {
    OwnershipScopeFromJSON,
    OwnershipScopeFromJSONTyped,
    OwnershipScopeToJSON,
    OwnershipScopeToJSONTyped,
} from './OwnershipScope.js';
import type { CapabilityRisk } from './CapabilityRisk.js';
import {
    CapabilityRiskFromJSON,
    CapabilityRiskFromJSONTyped,
    CapabilityRiskToJSON,
    CapabilityRiskToJSONTyped,
} from './CapabilityRisk.js';

/**
 * 
 * @export
 * @interface CapabilitySummary
 */
export interface CapabilitySummary {
    /**
     * Capability identifier, e.g. chat.post
     * @type {string}
     * @memberof CapabilitySummary
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CapabilitySummary
     */
    displayName: string;
    /**
     * 
     * @type {string}
     * @memberof CapabilitySummary
     */
    description: string;
    /**
     * 
     * @type {OwnershipScope}
     * @memberof CapabilitySummary
     */
    ownershipScope: OwnershipScope;
    /**
     * 
     * @type {CapabilityRisk}
     * @memberof CapabilitySummary
     */
    risk: CapabilityRisk;
}



/**
 * Check if a given object implements the CapabilitySummary interface.
 */
export function instanceOfCapabilitySummary(value: object): value is CapabilitySummary {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('ownershipScope' in value) || value['ownershipScope'] === undefined) return false;
    if (!('risk' in value) || value['risk'] === undefined) return false;
    return true;
}

export function CapabilitySummaryFromJSON(json: any): CapabilitySummary {
    return CapabilitySummaryFromJSONTyped(json, false);
}

export function CapabilitySummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): CapabilitySummary {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'displayName': json['displayName'],
        'description': json['description'],
        'ownershipScope': OwnershipScopeFromJSON(json['ownershipScope']),
        'risk': CapabilityRiskFromJSON(json['risk']),
    };
}

export function CapabilitySummaryToJSON(json: any): CapabilitySummary {
    return CapabilitySummaryToJSONTyped(json, false);
}

export function CapabilitySummaryToJSONTyped(value?: CapabilitySummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'displayName': value['displayName'],
        'description': value['description'],
        'ownershipScope': OwnershipScopeToJSON(value['ownershipScope']),
        'risk': CapabilityRiskToJSON(value['risk']),
    };
}

