/* tslint:disable */
/* eslint-disable */
/**
 * ConnectHub API
 * Unified integration, token, and proxy layer for Clancy Digital-Employees
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Connection } from './Connection.js';
import {
    ConnectionFromJSON,
    ConnectionFromJSONTyped,
    ConnectionToJSON,
    ConnectionToJSONTyped,
} from './Connection.js';

/**
 * 
 * @export
 * @interface ConnectionsGet200Response
 */
export interface ConnectionsGet200Response {
    /**
     * 
     * @type {Array<Connection>}
     * @memberof ConnectionsGet200Response
     */
    data: Array<Connection>;
    /**
     * 
     * @type {number}
     * @memberof ConnectionsGet200Response
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof ConnectionsGet200Response
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof ConnectionsGet200Response
     */
    limit: number;
}

/**
 * Check if a given object implements the ConnectionsGet200Response interface.
 */
export function instanceOfConnectionsGet200Response(value: object): value is ConnectionsGet200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    return true;
}

export function ConnectionsGet200ResponseFromJSON(json: any): ConnectionsGet200Response {
    return ConnectionsGet200ResponseFromJSONTyped(json, false);
}

export function ConnectionsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectionsGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ConnectionFromJSON)),
        'total': json['total'],
        'page': json['page'],
        'limit': json['limit'],
    };
}

export function ConnectionsGet200ResponseToJSON(json: any): ConnectionsGet200Response {
    return ConnectionsGet200ResponseToJSONTyped(json, false);
}

export function ConnectionsGet200ResponseToJSONTyped(value?: ConnectionsGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(ConnectionToJSON)),
        'total': value['total'],
        'page': value['page'],
        'limit': value['limit'],
    };
}

