/* tslint:disable */
/* eslint-disable */
/**
 * ConnectHub API
 * Unified integration, token, and proxy layer for Clancy Digital-Employees
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ConnectionStatus } from './ConnectionStatus.js';
import {
    ConnectionStatusFromJSON,
    ConnectionStatusFromJSONTyped,
    ConnectionStatusToJSON,
    ConnectionStatusToJSONTyped,
} from './ConnectionStatus.js';

/**
 * 
 * @export
 * @interface ConnectionsIdPatchRequest
 */
export interface ConnectionsIdPatchRequest {
    /**
     * 
     * @type {ConnectionStatus}
     * @memberof ConnectionsIdPatchRequest
     */
    status?: ConnectionStatus;
    /**
     * 
     * @type {string}
     * @memberof ConnectionsIdPatchRequest
     */
    employeeId?: string;
}



/**
 * Check if a given object implements the ConnectionsIdPatchRequest interface.
 */
export function instanceOfConnectionsIdPatchRequest(value: object): value is ConnectionsIdPatchRequest {
    return true;
}

export function ConnectionsIdPatchRequestFromJSON(json: any): ConnectionsIdPatchRequest {
    return ConnectionsIdPatchRequestFromJSONTyped(json, false);
}

export function ConnectionsIdPatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectionsIdPatchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : ConnectionStatusFromJSON(json['status']),
        'employeeId': json['employeeId'] == null ? undefined : json['employeeId'],
    };
}

export function ConnectionsIdPatchRequestToJSON(json: any): ConnectionsIdPatchRequest {
    return ConnectionsIdPatchRequestToJSONTyped(json, false);
}

export function ConnectionsIdPatchRequestToJSONTyped(value?: ConnectionsIdPatchRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': ConnectionStatusToJSON(value['status']),
        'employeeId': value['employeeId'],
    };
}

