/* tslint:disable */
/* eslint-disable */
/**
 * ConnectHub API
 * Unified integration, token, and proxy layer for Clancy Digital-Employees
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConnectionsGet200ResponseInner
 */
export interface ConnectionsGet200ResponseInner {
    /**
     * 
     * @type {string}
     * @memberof ConnectionsGet200ResponseInner
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ConnectionsGet200ResponseInner
     */
    orgId: string;
    /**
     * 
     * @type {string}
     * @memberof ConnectionsGet200ResponseInner
     */
    providerId: string;
    /**
     * 
     * @type {string}
     * @memberof ConnectionsGet200ResponseInner
     */
    displayName: string;
    /**
     * 
     * @type {string}
     * @memberof ConnectionsGet200ResponseInner
     */
    status: ConnectionsGet200ResponseInnerStatusEnum;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ConnectionsGet200ResponseInner
     */
    metadata: { [key: string]: any; };
}


/**
 * @export
 */
export const ConnectionsGet200ResponseInnerStatusEnum = {
    Active: 'active',
    Inactive: 'inactive',
    Error: 'error'
} as const;
export type ConnectionsGet200ResponseInnerStatusEnum = typeof ConnectionsGet200ResponseInnerStatusEnum[keyof typeof ConnectionsGet200ResponseInnerStatusEnum];


/**
 * Check if a given object implements the ConnectionsGet200ResponseInner interface.
 */
export function instanceOfConnectionsGet200ResponseInner(value: object): value is ConnectionsGet200ResponseInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('orgId' in value) || value['orgId'] === undefined) return false;
    if (!('providerId' in value) || value['providerId'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    return true;
}

export function ConnectionsGet200ResponseInnerFromJSON(json: any): ConnectionsGet200ResponseInner {
    return ConnectionsGet200ResponseInnerFromJSONTyped(json, false);
}

export function ConnectionsGet200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectionsGet200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'orgId': json['orgId'],
        'providerId': json['providerId'],
        'displayName': json['displayName'],
        'status': json['status'],
        'metadata': json['metadata'],
    };
}

export function ConnectionsGet200ResponseInnerToJSON(json: any): ConnectionsGet200ResponseInner {
    return ConnectionsGet200ResponseInnerToJSONTyped(json, false);
}

export function ConnectionsGet200ResponseInnerToJSONTyped(value?: ConnectionsGet200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'orgId': value['orgId'],
        'providerId': value['providerId'],
        'displayName': value['displayName'],
        'status': value['status'],
        'metadata': value['metadata'],
    };
}

