/* tslint:disable */
/* eslint-disable */
/**
 * ConnectHub API
 * Unified integration, token, and proxy layer for Clancy Digital-Employees
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface DocumentsDocumentIdDownloadGet200Response
 */
export interface DocumentsDocumentIdDownloadGet200Response {
    /**
     * Presigned S3 download URL
     * @type {string}
     * @memberof DocumentsDocumentIdDownloadGet200Response
     */
    downloadUrl: string;
    /**
     * Original filename
     * @type {string}
     * @memberof DocumentsDocumentIdDownloadGet200Response
     */
    filename: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentsDocumentIdDownloadGet200Response
     */
    mimeType?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentsDocumentIdDownloadGet200Response
     */
    sizeBytes?: string;
    /**
     * URL expiration time in seconds
     * @type {number}
     * @memberof DocumentsDocumentIdDownloadGet200Response
     */
    expiresIn: number;
}

/**
 * Check if a given object implements the DocumentsDocumentIdDownloadGet200Response interface.
 */
export function instanceOfDocumentsDocumentIdDownloadGet200Response(value: object): value is DocumentsDocumentIdDownloadGet200Response {
    if (!('downloadUrl' in value) || value['downloadUrl'] === undefined) return false;
    if (!('filename' in value) || value['filename'] === undefined) return false;
    if (!('expiresIn' in value) || value['expiresIn'] === undefined) return false;
    return true;
}

export function DocumentsDocumentIdDownloadGet200ResponseFromJSON(json: any): DocumentsDocumentIdDownloadGet200Response {
    return DocumentsDocumentIdDownloadGet200ResponseFromJSONTyped(json, false);
}

export function DocumentsDocumentIdDownloadGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentsDocumentIdDownloadGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'downloadUrl': json['downloadUrl'],
        'filename': json['filename'],
        'mimeType': json['mimeType'] == null ? undefined : json['mimeType'],
        'sizeBytes': json['sizeBytes'] == null ? undefined : json['sizeBytes'],
        'expiresIn': json['expiresIn'],
    };
}

export function DocumentsDocumentIdDownloadGet200ResponseToJSON(json: any): DocumentsDocumentIdDownloadGet200Response {
    return DocumentsDocumentIdDownloadGet200ResponseToJSONTyped(json, false);
}

export function DocumentsDocumentIdDownloadGet200ResponseToJSONTyped(value?: DocumentsDocumentIdDownloadGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'downloadUrl': value['downloadUrl'],
        'filename': value['filename'],
        'mimeType': value['mimeType'],
        'sizeBytes': value['sizeBytes'],
        'expiresIn': value['expiresIn'],
    };
}

