/* tslint:disable */
/* eslint-disable */
/**
 * ConnectHub API
 * Unified integration, token, and proxy layer for Clancy Digital-Employees
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Document } from './Document.js';
import {
    DocumentFromJSON,
    DocumentFromJSONTyped,
    DocumentToJSON,
    DocumentToJSONTyped,
} from './Document.js';

/**
 * 
 * @export
 * @interface DocumentsGet200Response
 */
export interface DocumentsGet200Response {
    /**
     * 
     * @type {Array<Document>}
     * @memberof DocumentsGet200Response
     */
    data: Array<Document>;
    /**
     * 
     * @type {number}
     * @memberof DocumentsGet200Response
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof DocumentsGet200Response
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof DocumentsGet200Response
     */
    limit: number;
}

/**
 * Check if a given object implements the DocumentsGet200Response interface.
 */
export function instanceOfDocumentsGet200Response(value: object): value is DocumentsGet200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    return true;
}

export function DocumentsGet200ResponseFromJSON(json: any): DocumentsGet200Response {
    return DocumentsGet200ResponseFromJSONTyped(json, false);
}

export function DocumentsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentsGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(DocumentFromJSON)),
        'total': json['total'],
        'page': json['page'],
        'limit': json['limit'],
    };
}

export function DocumentsGet200ResponseToJSON(json: any): DocumentsGet200Response {
    return DocumentsGet200ResponseToJSONTyped(json, false);
}

export function DocumentsGet200ResponseToJSONTyped(value?: DocumentsGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(DocumentToJSON)),
        'total': value['total'],
        'page': value['page'],
        'limit': value['limit'],
    };
}

