/* tslint:disable */
/* eslint-disable */
/**
 * ConnectHub API
 * Unified integration, token, and proxy layer for Clancy Digital-Employees
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface DocumentsDocumentIdDelete200Response
 */
export interface DocumentsDocumentIdDelete200Response {
    /**
     * Deletion status message
     * @type {string}
     * @memberof DocumentsDocumentIdDelete200Response
     */
    message: string;
    /**
     * ID of deleted document
     * @type {string}
     * @memberof DocumentsDocumentIdDelete200Response
     */
    documentId: string;
}

/**
 * Check if a given object implements the DocumentsDocumentIdDelete200Response interface.
 */
export function instanceOfDocumentsDocumentIdDelete200Response(value: object): value is DocumentsDocumentIdDelete200Response {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('documentId' in value) || value['documentId'] === undefined) return false;
    return true;
}

export function DocumentsDocumentIdDelete200ResponseFromJSON(json: any): DocumentsDocumentIdDelete200Response {
    return DocumentsDocumentIdDelete200ResponseFromJSONTyped(json, false);
}

export function DocumentsDocumentIdDelete200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentsDocumentIdDelete200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'documentId': json['documentId'],
    };
}

export function DocumentsDocumentIdDelete200ResponseToJSON(json: any): DocumentsDocumentIdDelete200Response {
    return DocumentsDocumentIdDelete200ResponseToJSONTyped(json, false);
}

export function DocumentsDocumentIdDelete200ResponseToJSONTyped(value?: DocumentsDocumentIdDelete200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'documentId': value['documentId'],
    };
}

