/* tslint:disable */
/* eslint-disable */
/**
 * ConnectHub API
 * Unified integration, token, and proxy layer for Clancy Digital-Employees
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface DocumentsFinalizePost200Response
 */
export interface DocumentsFinalizePost200Response {
    /**
     * Processing status
     * @type {string}
     * @memberof DocumentsFinalizePost200Response
     */
    status: string;
    /**
     * Status message
     * @type {string}
     * @memberof DocumentsFinalizePost200Response
     */
    message: string;
}

/**
 * Check if a given object implements the DocumentsFinalizePost200Response interface.
 */
export function instanceOfDocumentsFinalizePost200Response(value: object): value is DocumentsFinalizePost200Response {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function DocumentsFinalizePost200ResponseFromJSON(json: any): DocumentsFinalizePost200Response {
    return DocumentsFinalizePost200ResponseFromJSONTyped(json, false);
}

export function DocumentsFinalizePost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentsFinalizePost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'message': json['message'],
    };
}

export function DocumentsFinalizePost200ResponseToJSON(json: any): DocumentsFinalizePost200Response {
    return DocumentsFinalizePost200ResponseToJSONTyped(json, false);
}

export function DocumentsFinalizePost200ResponseToJSONTyped(value?: DocumentsFinalizePost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'message': value['message'],
    };
}

