/* tslint:disable */
/* eslint-disable */
/**
 * ConnectHub API
 * Unified integration, token, and proxy layer for Clancy Digital-Employees
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface DocumentsFinalizePostRequest
 */
export interface DocumentsFinalizePostRequest {
    /**
     * Document ID from presign response
     * @type {string}
     * @memberof DocumentsFinalizePostRequest
     */
    documentId: string;
    /**
     * S3 key from presign response
     * @type {string}
     * @memberof DocumentsFinalizePostRequest
     */
    key: string;
}

/**
 * Check if a given object implements the DocumentsFinalizePostRequest interface.
 */
export function instanceOfDocumentsFinalizePostRequest(value: object): value is DocumentsFinalizePostRequest {
    if (!('documentId' in value) || value['documentId'] === undefined) return false;
    if (!('key' in value) || value['key'] === undefined) return false;
    return true;
}

export function DocumentsFinalizePostRequestFromJSON(json: any): DocumentsFinalizePostRequest {
    return DocumentsFinalizePostRequestFromJSONTyped(json, false);
}

export function DocumentsFinalizePostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentsFinalizePostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'documentId': json['documentId'],
        'key': json['key'],
    };
}

export function DocumentsFinalizePostRequestToJSON(json: any): DocumentsFinalizePostRequest {
    return DocumentsFinalizePostRequestToJSONTyped(json, false);
}

export function DocumentsFinalizePostRequestToJSONTyped(value?: DocumentsFinalizePostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'documentId': value['documentId'],
        'key': value['key'],
    };
}

