/* tslint:disable */
/* eslint-disable */
/**
 * ConnectHub API
 * Unified integration, token, and proxy layer for Clancy Digital-Employees
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const DocumentStatus = {
    Registered: 'registered',
    Uploaded: 'uploaded',
    Processing: 'processing',
    Completed: 'completed',
    Failed: 'failed'
} as const;
export type DocumentStatus = typeof DocumentStatus[keyof typeof DocumentStatus];


export function instanceOfDocumentStatus(value: any): boolean {
    for (const key in DocumentStatus) {
        if (Object.prototype.hasOwnProperty.call(DocumentStatus, key)) {
            if (DocumentStatus[key as keyof typeof DocumentStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DocumentStatusFromJSON(json: any): DocumentStatus {
    return DocumentStatusFromJSONTyped(json, false);
}

export function DocumentStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentStatus {
    return json as DocumentStatus;
}

export function DocumentStatusToJSON(value?: DocumentStatus | null): any {
    return value as any;
}

export function DocumentStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): DocumentStatus {
    return value as DocumentStatus;
}

