/* tslint:disable */
/* eslint-disable */
/**
 * ConnectHub API
 * Unified integration, token, and proxy layer for Clancy Digital-Employees
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface DocumentsDocumentIdTagsPostRequest
 */
export interface DocumentsDocumentIdTagsPostRequest {
    /**
     * 
     * @type {string}
     * @memberof DocumentsDocumentIdTagsPostRequest
     */
    tagId: string;
}

/**
 * Check if a given object implements the DocumentsDocumentIdTagsPostRequest interface.
 */
export function instanceOfDocumentsDocumentIdTagsPostRequest(value: object): value is DocumentsDocumentIdTagsPostRequest {
    if (!('tagId' in value) || value['tagId'] === undefined) return false;
    return true;
}

export function DocumentsDocumentIdTagsPostRequestFromJSON(json: any): DocumentsDocumentIdTagsPostRequest {
    return DocumentsDocumentIdTagsPostRequestFromJSONTyped(json, false);
}

export function DocumentsDocumentIdTagsPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentsDocumentIdTagsPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'tagId': json['tagId'],
    };
}

export function DocumentsDocumentIdTagsPostRequestToJSON(json: any): DocumentsDocumentIdTagsPostRequest {
    return DocumentsDocumentIdTagsPostRequestToJSONTyped(json, false);
}

export function DocumentsDocumentIdTagsPostRequestToJSONTyped(value?: DocumentsDocumentIdTagsPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tagId': value['tagId'],
    };
}

