/* tslint:disable */
/* eslint-disable */
/**
 * ConnectHub API
 * Unified integration, token, and proxy layer for Clancy Digital-Employees
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Ownership scope (defaults to 'organization')
 * @export
 * @interface DocumentsPresignPostRequestOwnershipScope
 */
export interface DocumentsPresignPostRequestOwnershipScope {
}

/**
 * Check if a given object implements the DocumentsPresignPostRequestOwnershipScope interface.
 */
export function instanceOfDocumentsPresignPostRequestOwnershipScope(value: object): value is DocumentsPresignPostRequestOwnershipScope {
    return true;
}

export function DocumentsPresignPostRequestOwnershipScopeFromJSON(json: any): DocumentsPresignPostRequestOwnershipScope {
    return DocumentsPresignPostRequestOwnershipScopeFromJSONTyped(json, false);
}

export function DocumentsPresignPostRequestOwnershipScopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentsPresignPostRequestOwnershipScope {
    return json;
}

export function DocumentsPresignPostRequestOwnershipScopeToJSON(json: any): DocumentsPresignPostRequestOwnershipScope {
    return DocumentsPresignPostRequestOwnershipScopeToJSONTyped(json, false);
}

export function DocumentsPresignPostRequestOwnershipScopeToJSONTyped(value?: DocumentsPresignPostRequestOwnershipScope | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

