/* tslint:disable */
/* eslint-disable */
/**
 * ConnectHub API
 * Unified integration, token, and proxy layer for Clancy Digital-Employees
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { DocumentStatus } from './DocumentStatus.js';
import {
    DocumentStatusFromJSON,
    DocumentStatusFromJSONTyped,
    DocumentStatusToJSON,
    DocumentStatusToJSONTyped,
} from './DocumentStatus.js';

/**
 * 
 * @export
 * @interface DocumentsDocumentIdStatusGet200Response
 */
export interface DocumentsDocumentIdStatusGet200Response {
    /**
     * 
     * @type {string}
     * @memberof DocumentsDocumentIdStatusGet200Response
     */
    documentId: string;
    /**
     * 
     * @type {DocumentStatus}
     * @memberof DocumentsDocumentIdStatusGet200Response
     */
    status: DocumentStatus;
    /**
     * 
     * @type {string}
     * @memberof DocumentsDocumentIdStatusGet200Response
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentsDocumentIdStatusGet200Response
     */
    mimeType?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentsDocumentIdStatusGet200Response
     */
    sizeBytes?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentsDocumentIdStatusGet200Response
     */
    error?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentsDocumentIdStatusGet200Response
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentsDocumentIdStatusGet200Response
     */
    updatedAt: string;
}



/**
 * Check if a given object implements the DocumentsDocumentIdStatusGet200Response interface.
 */
export function instanceOfDocumentsDocumentIdStatusGet200Response(value: object): value is DocumentsDocumentIdStatusGet200Response {
    if (!('documentId' in value) || value['documentId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function DocumentsDocumentIdStatusGet200ResponseFromJSON(json: any): DocumentsDocumentIdStatusGet200Response {
    return DocumentsDocumentIdStatusGet200ResponseFromJSONTyped(json, false);
}

export function DocumentsDocumentIdStatusGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentsDocumentIdStatusGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'documentId': json['documentId'],
        'status': DocumentStatusFromJSON(json['status']),
        'title': json['title'] == null ? undefined : json['title'],
        'mimeType': json['mimeType'] == null ? undefined : json['mimeType'],
        'sizeBytes': json['sizeBytes'] == null ? undefined : json['sizeBytes'],
        'error': json['error'] == null ? undefined : json['error'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
    };
}

export function DocumentsDocumentIdStatusGet200ResponseToJSON(json: any): DocumentsDocumentIdStatusGet200Response {
    return DocumentsDocumentIdStatusGet200ResponseToJSONTyped(json, false);
}

export function DocumentsDocumentIdStatusGet200ResponseToJSONTyped(value?: DocumentsDocumentIdStatusGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'documentId': value['documentId'],
        'status': DocumentStatusToJSON(value['status']),
        'title': value['title'],
        'mimeType': value['mimeType'],
        'sizeBytes': value['sizeBytes'],
        'error': value['error'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
    };
}

