/* tslint:disable */
/* eslint-disable */
/**
 * ConnectHub API
 * Unified integration, token, and proxy layer for Clancy Digital-Employees
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface DocumentsDocumentIdTagsPost200Response
 */
export interface DocumentsDocumentIdTagsPost200Response {
    /**
     * 
     * @type {string}
     * @memberof DocumentsDocumentIdTagsPost200Response
     */
    status: DocumentsDocumentIdTagsPost200ResponseStatusEnum;
}


/**
 * @export
 */
export const DocumentsDocumentIdTagsPost200ResponseStatusEnum = {
    Ok: 'ok'
} as const;
export type DocumentsDocumentIdTagsPost200ResponseStatusEnum = typeof DocumentsDocumentIdTagsPost200ResponseStatusEnum[keyof typeof DocumentsDocumentIdTagsPost200ResponseStatusEnum];


/**
 * Check if a given object implements the DocumentsDocumentIdTagsPost200Response interface.
 */
export function instanceOfDocumentsDocumentIdTagsPost200Response(value: object): value is DocumentsDocumentIdTagsPost200Response {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function DocumentsDocumentIdTagsPost200ResponseFromJSON(json: any): DocumentsDocumentIdTagsPost200Response {
    return DocumentsDocumentIdTagsPost200ResponseFromJSONTyped(json, false);
}

export function DocumentsDocumentIdTagsPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentsDocumentIdTagsPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
    };
}

export function DocumentsDocumentIdTagsPost200ResponseToJSON(json: any): DocumentsDocumentIdTagsPost200Response {
    return DocumentsDocumentIdTagsPost200ResponseToJSONTyped(json, false);
}

export function DocumentsDocumentIdTagsPost200ResponseToJSONTyped(value?: DocumentsDocumentIdTagsPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
    };
}

