/* tslint:disable */
/* eslint-disable */
/**
 * ConnectHub API
 * Unified integration, token, and proxy layer for Clancy Digital-Employees
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface DocumentsPresignPost200Response
 */
export interface DocumentsPresignPost200Response {
    /**
     * Presigned S3 upload URL
     * @type {string}
     * @memberof DocumentsPresignPost200Response
     */
    uploadUrl: string;
    /**
     * S3 object key
     * @type {string}
     * @memberof DocumentsPresignPost200Response
     */
    key: string;
    /**
     * Generated document ID
     * @type {string}
     * @memberof DocumentsPresignPost200Response
     */
    documentId: string;
}

/**
 * Check if a given object implements the DocumentsPresignPost200Response interface.
 */
export function instanceOfDocumentsPresignPost200Response(value: object): value is DocumentsPresignPost200Response {
    if (!('uploadUrl' in value) || value['uploadUrl'] === undefined) return false;
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('documentId' in value) || value['documentId'] === undefined) return false;
    return true;
}

export function DocumentsPresignPost200ResponseFromJSON(json: any): DocumentsPresignPost200Response {
    return DocumentsPresignPost200ResponseFromJSONTyped(json, false);
}

export function DocumentsPresignPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentsPresignPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'uploadUrl': json['uploadUrl'],
        'key': json['key'],
        'documentId': json['documentId'],
    };
}

export function DocumentsPresignPost200ResponseToJSON(json: any): DocumentsPresignPost200Response {
    return DocumentsPresignPost200ResponseToJSONTyped(json, false);
}

export function DocumentsPresignPost200ResponseToJSONTyped(value?: DocumentsPresignPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uploadUrl': value['uploadUrl'],
        'key': value['key'],
        'documentId': value['documentId'],
    };
}

