/* tslint:disable */
/* eslint-disable */
/**
 * ConnectHub API
 * Unified integration, token, and proxy layer for Clancy Digital-Employees
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface HealthGet200ResponseStatus
 */
export interface HealthGet200ResponseStatus {
}

/**
 * Check if a given object implements the HealthGet200ResponseStatus interface.
 */
export function instanceOfHealthGet200ResponseStatus(value: object): value is HealthGet200ResponseStatus {
    return true;
}

export function HealthGet200ResponseStatusFromJSON(json: any): HealthGet200ResponseStatus {
    return HealthGet200ResponseStatusFromJSONTyped(json, false);
}

export function HealthGet200ResponseStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthGet200ResponseStatus {
    return json;
}

export function HealthGet200ResponseStatusToJSON(json: any): HealthGet200ResponseStatus {
    return HealthGet200ResponseStatusToJSONTyped(json, false);
}

export function HealthGet200ResponseStatusToJSONTyped(value?: HealthGet200ResponseStatus | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

