/* tslint:disable */
/* eslint-disable */
/**
 * ConnectHub API
 * Unified integration, token, and proxy layer for Clancy Digital-Employees
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HealthGet200ResponseDependenciesDatabase
 */
export interface HealthGet200ResponseDependenciesDatabase {
}

/**
 * Check if a given object implements the HealthGet200ResponseDependenciesDatabase interface.
 */
export function instanceOfHealthGet200ResponseDependenciesDatabase(value: object): value is HealthGet200ResponseDependenciesDatabase {
    return true;
}

export function HealthGet200ResponseDependenciesDatabaseFromJSON(json: any): HealthGet200ResponseDependenciesDatabase {
    return HealthGet200ResponseDependenciesDatabaseFromJSONTyped(json, false);
}

export function HealthGet200ResponseDependenciesDatabaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthGet200ResponseDependenciesDatabase {
    return json;
}

export function HealthGet200ResponseDependenciesDatabaseToJSON(json: any): HealthGet200ResponseDependenciesDatabase {
    return HealthGet200ResponseDependenciesDatabaseToJSONTyped(json, false);
}

export function HealthGet200ResponseDependenciesDatabaseToJSONTyped(value?: HealthGet200ResponseDependenciesDatabase | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

