/* tslint:disable */
/* eslint-disable */
/**
 * ConnectHub API
 * Unified integration, token, and proxy layer for Clancy Digital-Employees
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HealthGet200ResponseDependenciesDatabase } from './HealthGet200ResponseDependenciesDatabase';
import {
    HealthGet200ResponseDependenciesDatabaseFromJSON,
    HealthGet200ResponseDependenciesDatabaseFromJSONTyped,
    HealthGet200ResponseDependenciesDatabaseToJSON,
    HealthGet200ResponseDependenciesDatabaseToJSONTyped,
} from './HealthGet200ResponseDependenciesDatabase';

/**
 * 
 * @export
 * @interface HealthGet200ResponseDependencies
 */
export interface HealthGet200ResponseDependencies {
    /**
     * 
     * @type {HealthGet200ResponseDependenciesDatabase}
     * @memberof HealthGet200ResponseDependencies
     */
    database: HealthGet200ResponseDependenciesDatabase;
    /**
     * 
     * @type {HealthGet200ResponseDependenciesDatabase}
     * @memberof HealthGet200ResponseDependencies
     */
    auth0: HealthGet200ResponseDependenciesDatabase;
}

/**
 * Check if a given object implements the HealthGet200ResponseDependencies interface.
 */
export function instanceOfHealthGet200ResponseDependencies(value: object): value is HealthGet200ResponseDependencies {
    if (!('database' in value) || value['database'] === undefined) return false;
    if (!('auth0' in value) || value['auth0'] === undefined) return false;
    return true;
}

export function HealthGet200ResponseDependenciesFromJSON(json: any): HealthGet200ResponseDependencies {
    return HealthGet200ResponseDependenciesFromJSONTyped(json, false);
}

export function HealthGet200ResponseDependenciesFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthGet200ResponseDependencies {
    if (json == null) {
        return json;
    }
    return {
        
        'database': HealthGet200ResponseDependenciesDatabaseFromJSON(json['database']),
        'auth0': HealthGet200ResponseDependenciesDatabaseFromJSON(json['auth0']),
    };
}

export function HealthGet200ResponseDependenciesToJSON(json: any): HealthGet200ResponseDependencies {
    return HealthGet200ResponseDependenciesToJSONTyped(json, false);
}

export function HealthGet200ResponseDependenciesToJSONTyped(value?: HealthGet200ResponseDependencies | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'database': HealthGet200ResponseDependenciesDatabaseToJSON(value['database']),
        'auth0': HealthGet200ResponseDependenciesDatabaseToJSON(value['auth0']),
    };
}

