/* tslint:disable */
/* eslint-disable */
/**
 * ConnectHub API
 * Unified integration, token, and proxy layer for Clancy Digital-Employees
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface KnowledgeSnippetOrigin
 */
export interface KnowledgeSnippetOrigin {
}

/**
 * Check if a given object implements the KnowledgeSnippetOrigin interface.
 */
export function instanceOfKnowledgeSnippetOrigin(value: object): value is KnowledgeSnippetOrigin {
    return true;
}

export function KnowledgeSnippetOriginFromJSON(json: any): KnowledgeSnippetOrigin {
    return KnowledgeSnippetOriginFromJSONTyped(json, false);
}

export function KnowledgeSnippetOriginFromJSONTyped(json: any, ignoreDiscriminator: boolean): KnowledgeSnippetOrigin {
    return json;
}

export function KnowledgeSnippetOriginToJSON(json: any): KnowledgeSnippetOrigin {
    return KnowledgeSnippetOriginToJSONTyped(json, false);
}

export function KnowledgeSnippetOriginToJSONTyped(value?: KnowledgeSnippetOrigin | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

