/* tslint:disable */
/* eslint-disable */
/**
 * ConnectHub API
 * Unified integration, token, and proxy layer for Clancy Digital-Employees
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { KnowledgeSnippetsBulkPostRequestSnippetsInner } from './KnowledgeSnippetsBulkPostRequestSnippetsInner.js';
import {
    KnowledgeSnippetsBulkPostRequestSnippetsInnerFromJSON,
    KnowledgeSnippetsBulkPostRequestSnippetsInnerFromJSONTyped,
    KnowledgeSnippetsBulkPostRequestSnippetsInnerToJSON,
    KnowledgeSnippetsBulkPostRequestSnippetsInnerToJSONTyped,
} from './KnowledgeSnippetsBulkPostRequestSnippetsInner.js';
import type { KnowledgeSnippetsBulkPostRequestOwnershipScope } from './KnowledgeSnippetsBulkPostRequestOwnershipScope.js';
import {
    KnowledgeSnippetsBulkPostRequestOwnershipScopeFromJSON,
    KnowledgeSnippetsBulkPostRequestOwnershipScopeFromJSONTyped,
    KnowledgeSnippetsBulkPostRequestOwnershipScopeToJSON,
    KnowledgeSnippetsBulkPostRequestOwnershipScopeToJSONTyped,
} from './KnowledgeSnippetsBulkPostRequestOwnershipScope.js';

/**
 * 
 * @export
 * @interface KnowledgeSnippetsBulkPostRequest
 */
export interface KnowledgeSnippetsBulkPostRequest {
    /**
     * 
     * @type {string}
     * @memberof KnowledgeSnippetsBulkPostRequest
     */
    orgId: string;
    /**
     * 
     * @type {string}
     * @memberof KnowledgeSnippetsBulkPostRequest
     */
    documentId: string;
    /**
     * 
     * @type {KnowledgeSnippetsBulkPostRequestOwnershipScope}
     * @memberof KnowledgeSnippetsBulkPostRequest
     */
    ownershipScope: KnowledgeSnippetsBulkPostRequestOwnershipScope;
    /**
     * 
     * @type {string}
     * @memberof KnowledgeSnippetsBulkPostRequest
     */
    ownerId?: string;
    /**
     * 
     * @type {Array<KnowledgeSnippetsBulkPostRequestSnippetsInner>}
     * @memberof KnowledgeSnippetsBulkPostRequest
     */
    snippets: Array<KnowledgeSnippetsBulkPostRequestSnippetsInner>;
}

/**
 * Check if a given object implements the KnowledgeSnippetsBulkPostRequest interface.
 */
export function instanceOfKnowledgeSnippetsBulkPostRequest(value: object): value is KnowledgeSnippetsBulkPostRequest {
    if (!('orgId' in value) || value['orgId'] === undefined) return false;
    if (!('documentId' in value) || value['documentId'] === undefined) return false;
    if (!('ownershipScope' in value) || value['ownershipScope'] === undefined) return false;
    if (!('snippets' in value) || value['snippets'] === undefined) return false;
    return true;
}

export function KnowledgeSnippetsBulkPostRequestFromJSON(json: any): KnowledgeSnippetsBulkPostRequest {
    return KnowledgeSnippetsBulkPostRequestFromJSONTyped(json, false);
}

export function KnowledgeSnippetsBulkPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): KnowledgeSnippetsBulkPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'orgId': json['orgId'],
        'documentId': json['documentId'],
        'ownershipScope': KnowledgeSnippetsBulkPostRequestOwnershipScopeFromJSON(json['ownershipScope']),
        'ownerId': json['ownerId'] == null ? undefined : json['ownerId'],
        'snippets': ((json['snippets'] as Array<any>).map(KnowledgeSnippetsBulkPostRequestSnippetsInnerFromJSON)),
    };
}

export function KnowledgeSnippetsBulkPostRequestToJSON(json: any): KnowledgeSnippetsBulkPostRequest {
    return KnowledgeSnippetsBulkPostRequestToJSONTyped(json, false);
}

export function KnowledgeSnippetsBulkPostRequestToJSONTyped(value?: KnowledgeSnippetsBulkPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'orgId': value['orgId'],
        'documentId': value['documentId'],
        'ownershipScope': KnowledgeSnippetsBulkPostRequestOwnershipScopeToJSON(value['ownershipScope']),
        'ownerId': value['ownerId'],
        'snippets': ((value['snippets'] as Array<any>).map(KnowledgeSnippetsBulkPostRequestSnippetsInnerToJSON)),
    };
}

