/* tslint:disable */
/* eslint-disable */
/**
 * ConnectHub API
 * Unified integration, token, and proxy layer for Clancy Digital-Employees
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { KnowledgeSnippetOrigin } from './KnowledgeSnippetOrigin.js';
import {
    KnowledgeSnippetOriginFromJSON,
    KnowledgeSnippetOriginFromJSONTyped,
    KnowledgeSnippetOriginToJSON,
    KnowledgeSnippetOriginToJSONTyped,
} from './KnowledgeSnippetOrigin.js';
import type { KnowledgeSnippetsBulkPostRequestOwnershipScope } from './KnowledgeSnippetsBulkPostRequestOwnershipScope.js';
import {
    KnowledgeSnippetsBulkPostRequestOwnershipScopeFromJSON,
    KnowledgeSnippetsBulkPostRequestOwnershipScopeFromJSONTyped,
    KnowledgeSnippetsBulkPostRequestOwnershipScopeToJSON,
    KnowledgeSnippetsBulkPostRequestOwnershipScopeToJSONTyped,
} from './KnowledgeSnippetsBulkPostRequestOwnershipScope.js';

/**
 * 
 * @export
 * @interface KnowledgeSnippet
 */
export interface KnowledgeSnippet {
    /**
     * 
     * @type {string}
     * @memberof KnowledgeSnippet
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof KnowledgeSnippet
     */
    orgId: string;
    /**
     * 
     * @type {string}
     * @memberof KnowledgeSnippet
     */
    sourceRunId?: string;
    /**
     * 
     * @type {KnowledgeSnippetOrigin}
     * @memberof KnowledgeSnippet
     */
    origin: KnowledgeSnippetOrigin;
    /**
     * 
     * @type {string}
     * @memberof KnowledgeSnippet
     */
    summary?: string;
    /**
     * 
     * @type {string}
     * @memberof KnowledgeSnippet
     */
    blob?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof KnowledgeSnippet
     */
    metadata: { [key: string]: any; };
    /**
     * 
     * @type {KnowledgeSnippetsBulkPostRequestOwnershipScope}
     * @memberof KnowledgeSnippet
     */
    ownershipScope?: KnowledgeSnippetsBulkPostRequestOwnershipScope;
    /**
     * 
     * @type {string}
     * @memberof KnowledgeSnippet
     */
    ownerId?: string;
    /**
     * 
     * @type {string}
     * @memberof KnowledgeSnippet
     */
    documentId?: string;
    /**
     * 
     * @type {number}
     * @memberof KnowledgeSnippet
     */
    chunkIndex?: number;
    /**
     * 
     * @type {number}
     * @memberof KnowledgeSnippet
     */
    chunkCount?: number;
    /**
     * 
     * @type {string}
     * @memberof KnowledgeSnippet
     */
    checksum?: string;
    /**
     * 
     * @type {Date}
     * @memberof KnowledgeSnippet
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the KnowledgeSnippet interface.
 */
export function instanceOfKnowledgeSnippet(value: object): value is KnowledgeSnippet {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('orgId' in value) || value['orgId'] === undefined) return false;
    if (!('origin' in value) || value['origin'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function KnowledgeSnippetFromJSON(json: any): KnowledgeSnippet {
    return KnowledgeSnippetFromJSONTyped(json, false);
}

export function KnowledgeSnippetFromJSONTyped(json: any, ignoreDiscriminator: boolean): KnowledgeSnippet {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'orgId': json['orgId'],
        'sourceRunId': json['sourceRunId'] == null ? undefined : json['sourceRunId'],
        'origin': KnowledgeSnippetOriginFromJSON(json['origin']),
        'summary': json['summary'] == null ? undefined : json['summary'],
        'blob': json['blob'] == null ? undefined : json['blob'],
        'metadata': json['metadata'],
        'ownershipScope': json['ownershipScope'] == null ? undefined : KnowledgeSnippetsBulkPostRequestOwnershipScopeFromJSON(json['ownershipScope']),
        'ownerId': json['ownerId'] == null ? undefined : json['ownerId'],
        'documentId': json['documentId'] == null ? undefined : json['documentId'],
        'chunkIndex': json['chunkIndex'] == null ? undefined : json['chunkIndex'],
        'chunkCount': json['chunkCount'] == null ? undefined : json['chunkCount'],
        'checksum': json['checksum'] == null ? undefined : json['checksum'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function KnowledgeSnippetToJSON(json: any): KnowledgeSnippet {
    return KnowledgeSnippetToJSONTyped(json, false);
}

export function KnowledgeSnippetToJSONTyped(value?: KnowledgeSnippet | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'orgId': value['orgId'],
        'sourceRunId': value['sourceRunId'],
        'origin': KnowledgeSnippetOriginToJSON(value['origin']),
        'summary': value['summary'],
        'blob': value['blob'],
        'metadata': value['metadata'],
        'ownershipScope': KnowledgeSnippetsBulkPostRequestOwnershipScopeToJSON(value['ownershipScope']),
        'ownerId': value['ownerId'],
        'documentId': value['documentId'],
        'chunkIndex': value['chunkIndex'],
        'chunkCount': value['chunkCount'],
        'checksum': value['checksum'],
        'createdAt': ((value['createdAt']).toISOString()),
    };
}

