/* tslint:disable */
/* eslint-disable */
/**
 * ConnectHub API
 * Unified integration, token, and proxy layer for Clancy Digital-Employees
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { KnowledgeSnippet } from './KnowledgeSnippet.js';
import {
    KnowledgeSnippetFromJSON,
    KnowledgeSnippetFromJSONTyped,
    KnowledgeSnippetToJSON,
    KnowledgeSnippetToJSONTyped,
} from './KnowledgeSnippet.js';

/**
 * 
 * @export
 * @interface KnowledgeSnippetsGet200Response
 */
export interface KnowledgeSnippetsGet200Response {
    /**
     * 
     * @type {Array<KnowledgeSnippet>}
     * @memberof KnowledgeSnippetsGet200Response
     */
    data: Array<KnowledgeSnippet>;
    /**
     * 
     * @type {number}
     * @memberof KnowledgeSnippetsGet200Response
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof KnowledgeSnippetsGet200Response
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof KnowledgeSnippetsGet200Response
     */
    limit: number;
}

/**
 * Check if a given object implements the KnowledgeSnippetsGet200Response interface.
 */
export function instanceOfKnowledgeSnippetsGet200Response(value: object): value is KnowledgeSnippetsGet200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    return true;
}

export function KnowledgeSnippetsGet200ResponseFromJSON(json: any): KnowledgeSnippetsGet200Response {
    return KnowledgeSnippetsGet200ResponseFromJSONTyped(json, false);
}

export function KnowledgeSnippetsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): KnowledgeSnippetsGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(KnowledgeSnippetFromJSON)),
        'total': json['total'],
        'page': json['page'],
        'limit': json['limit'],
    };
}

export function KnowledgeSnippetsGet200ResponseToJSON(json: any): KnowledgeSnippetsGet200Response {
    return KnowledgeSnippetsGet200ResponseToJSONTyped(json, false);
}

export function KnowledgeSnippetsGet200ResponseToJSONTyped(value?: KnowledgeSnippetsGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(KnowledgeSnippetToJSON)),
        'total': value['total'],
        'page': value['page'],
        'limit': value['limit'],
    };
}

