/* tslint:disable */
/* eslint-disable */
/**
 * ConnectHub API
 * Unified integration, token, and proxy layer for Clancy Digital-Employees
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface KnowledgeSnippetsBulkPost200Response
 */
export interface KnowledgeSnippetsBulkPost200Response {
    /**
     * Number of snippets inserted
     * @type {number}
     * @memberof KnowledgeSnippetsBulkPost200Response
     */
    inserted: number;
    /**
     * Number of duplicates skipped
     * @type {number}
     * @memberof KnowledgeSnippetsBulkPost200Response
     */
    duplicates: number;
}

/**
 * Check if a given object implements the KnowledgeSnippetsBulkPost200Response interface.
 */
export function instanceOfKnowledgeSnippetsBulkPost200Response(value: object): value is KnowledgeSnippetsBulkPost200Response {
    if (!('inserted' in value) || value['inserted'] === undefined) return false;
    if (!('duplicates' in value) || value['duplicates'] === undefined) return false;
    return true;
}

export function KnowledgeSnippetsBulkPost200ResponseFromJSON(json: any): KnowledgeSnippetsBulkPost200Response {
    return KnowledgeSnippetsBulkPost200ResponseFromJSONTyped(json, false);
}

export function KnowledgeSnippetsBulkPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): KnowledgeSnippetsBulkPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'inserted': json['inserted'],
        'duplicates': json['duplicates'],
    };
}

export function KnowledgeSnippetsBulkPost200ResponseToJSON(json: any): KnowledgeSnippetsBulkPost200Response {
    return KnowledgeSnippetsBulkPost200ResponseToJSONTyped(json, false);
}

export function KnowledgeSnippetsBulkPost200ResponseToJSONTyped(value?: KnowledgeSnippetsBulkPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'inserted': value['inserted'],
        'duplicates': value['duplicates'],
    };
}

