/* tslint:disable */
/* eslint-disable */
/**
 * ConnectHub API
 * Unified integration, token, and proxy layer for Clancy Digital-Employees
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OauthCallbackProviderGet400Response
 */
export interface OauthCallbackProviderGet400Response {
    /**
     * 
     * @type {string}
     * @memberof OauthCallbackProviderGet400Response
     */
    status: OauthCallbackProviderGet400ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof OauthCallbackProviderGet400Response
     */
    error: string;
    /**
     * 
     * @type {string}
     * @memberof OauthCallbackProviderGet400Response
     */
    errorDescription?: string;
    /**
     * 
     * @type {string}
     * @memberof OauthCallbackProviderGet400Response
     */
    provider: string;
    /**
     * 
     * @type {string}
     * @memberof OauthCallbackProviderGet400Response
     */
    redirectUrl?: string;
}


/**
 * @export
 */
export const OauthCallbackProviderGet400ResponseStatusEnum = {
    Failed: 'failed'
} as const;
export type OauthCallbackProviderGet400ResponseStatusEnum = typeof OauthCallbackProviderGet400ResponseStatusEnum[keyof typeof OauthCallbackProviderGet400ResponseStatusEnum];


/**
 * Check if a given object implements the OauthCallbackProviderGet400Response interface.
 */
export function instanceOfOauthCallbackProviderGet400Response(value: object): value is OauthCallbackProviderGet400Response {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    return true;
}

export function OauthCallbackProviderGet400ResponseFromJSON(json: any): OauthCallbackProviderGet400Response {
    return OauthCallbackProviderGet400ResponseFromJSONTyped(json, false);
}

export function OauthCallbackProviderGet400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OauthCallbackProviderGet400Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'error': json['error'],
        'errorDescription': json['errorDescription'] == null ? undefined : json['errorDescription'],
        'provider': json['provider'],
        'redirectUrl': json['redirectUrl'] == null ? undefined : json['redirectUrl'],
    };
}

export function OauthCallbackProviderGet400ResponseToJSON(json: any): OauthCallbackProviderGet400Response {
    return OauthCallbackProviderGet400ResponseToJSONTyped(json, false);
}

export function OauthCallbackProviderGet400ResponseToJSONTyped(value?: OauthCallbackProviderGet400Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'error': value['error'],
        'errorDescription': value['errorDescription'],
        'provider': value['provider'],
        'redirectUrl': value['redirectUrl'],
    };
}

