/* tslint:disable */
/* eslint-disable */
/**
 * ConnectHub API
 * Unified integration, token, and proxy layer for Clancy Digital-Employees
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const OauthConnectionStatus = {
    Connected: 'connected',
    NeedsAuth: 'needs_auth',
    NeedsScopeUpgrade: 'needs_scope_upgrade'
} as const;
export type OauthConnectionStatus = typeof OauthConnectionStatus[keyof typeof OauthConnectionStatus];


export function instanceOfOauthConnectionStatus(value: any): boolean {
    for (const key in OauthConnectionStatus) {
        if (Object.prototype.hasOwnProperty.call(OauthConnectionStatus, key)) {
            if (OauthConnectionStatus[key as keyof typeof OauthConnectionStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function OauthConnectionStatusFromJSON(json: any): OauthConnectionStatus {
    return OauthConnectionStatusFromJSONTyped(json, false);
}

export function OauthConnectionStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): OauthConnectionStatus {
    return json as OauthConnectionStatus;
}

export function OauthConnectionStatusToJSON(value?: OauthConnectionStatus | null): any {
    return value as any;
}

export function OauthConnectionStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): OauthConnectionStatus {
    return value as OauthConnectionStatus;
}

