/* tslint:disable */
/* eslint-disable */
/**
 * ConnectHub API
 * Unified integration, token, and proxy layer for Clancy Digital-Employees
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface OAuthErrorResponse
 */
export interface OAuthErrorResponse {
    /**
     * 
     * @type {string}
     * @memberof OAuthErrorResponse
     */
    status: OAuthErrorResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof OAuthErrorResponse
     */
    error: string;
    /**
     * 
     * @type {string}
     * @memberof OAuthErrorResponse
     */
    errorDescription?: string;
    /**
     * 
     * @type {string}
     * @memberof OAuthErrorResponse
     */
    provider: string;
    /**
     * 
     * @type {string}
     * @memberof OAuthErrorResponse
     */
    redirectUrl?: string;
}


/**
 * @export
 */
export const OAuthErrorResponseStatusEnum = {
    Failed: 'failed'
} as const;
export type OAuthErrorResponseStatusEnum = typeof OAuthErrorResponseStatusEnum[keyof typeof OAuthErrorResponseStatusEnum];


/**
 * Check if a given object implements the OAuthErrorResponse interface.
 */
export function instanceOfOAuthErrorResponse(value: object): value is OAuthErrorResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    return true;
}

export function OAuthErrorResponseFromJSON(json: any): OAuthErrorResponse {
    return OAuthErrorResponseFromJSONTyped(json, false);
}

export function OAuthErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OAuthErrorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'error': json['error'],
        'errorDescription': json['errorDescription'] == null ? undefined : json['errorDescription'],
        'provider': json['provider'],
        'redirectUrl': json['redirectUrl'] == null ? undefined : json['redirectUrl'],
    };
}

export function OAuthErrorResponseToJSON(json: any): OAuthErrorResponse {
    return OAuthErrorResponseToJSONTyped(json, false);
}

export function OAuthErrorResponseToJSONTyped(value?: OAuthErrorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'error': value['error'],
        'errorDescription': value['errorDescription'],
        'provider': value['provider'],
        'redirectUrl': value['redirectUrl'],
    };
}

