/* tslint:disable */
/* eslint-disable */
/**
 * ConnectHub API
 * Unified integration, token, and proxy layer for Clancy Digital-Employees
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OauthAuditPost200ResponseInnerStatus
 */
export interface OauthAuditPost200ResponseInnerStatus {
}

/**
 * Check if a given object implements the OauthAuditPost200ResponseInnerStatus interface.
 */
export function instanceOfOauthAuditPost200ResponseInnerStatus(value: object): value is OauthAuditPost200ResponseInnerStatus {
    return true;
}

export function OauthAuditPost200ResponseInnerStatusFromJSON(json: any): OauthAuditPost200ResponseInnerStatus {
    return OauthAuditPost200ResponseInnerStatusFromJSONTyped(json, false);
}

export function OauthAuditPost200ResponseInnerStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): OauthAuditPost200ResponseInnerStatus {
    return json;
}

export function OauthAuditPost200ResponseInnerStatusToJSON(json: any): OauthAuditPost200ResponseInnerStatus {
    return OauthAuditPost200ResponseInnerStatusToJSONTyped(json, false);
}

export function OauthAuditPost200ResponseInnerStatusToJSONTyped(value?: OauthAuditPost200ResponseInnerStatus | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

