/* tslint:disable */
/* eslint-disable */
/**
 * ConnectHub API
 * Unified integration, token, and proxy layer for Clancy Digital-Employees
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface OauthAuditPost400Response
 */
export interface OauthAuditPost400Response {
    /**
     * 
     * @type {string}
     * @memberof OauthAuditPost400Response
     */
    error: string;
    /**
     * 
     * @type {string}
     * @memberof OauthAuditPost400Response
     */
    message: string;
}

/**
 * Check if a given object implements the OauthAuditPost400Response interface.
 */
export function instanceOfOauthAuditPost400Response(value: object): value is OauthAuditPost400Response {
    if (!('error' in value) || value['error'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function OauthAuditPost400ResponseFromJSON(json: any): OauthAuditPost400Response {
    return OauthAuditPost400ResponseFromJSONTyped(json, false);
}

export function OauthAuditPost400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OauthAuditPost400Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'],
        'message': json['message'],
    };
}

export function OauthAuditPost400ResponseToJSON(json: any): OauthAuditPost400Response {
    return OauthAuditPost400ResponseToJSONTyped(json, false);
}

export function OauthAuditPost400ResponseToJSONTyped(value?: OauthAuditPost400Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
        'message': value['message'],
    };
}

