/* tslint:disable */
/* eslint-disable */
/**
 * ConnectHub API
 * Unified integration, token, and proxy layer for Clancy Digital-Employees
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { OauthAuditPost200ResponseInnerStatus } from './OauthAuditPost200ResponseInnerStatus.js';
import {
    OauthAuditPost200ResponseInnerStatusFromJSON,
    OauthAuditPost200ResponseInnerStatusFromJSONTyped,
    OauthAuditPost200ResponseInnerStatusToJSON,
    OauthAuditPost200ResponseInnerStatusToJSONTyped,
} from './OauthAuditPost200ResponseInnerStatus.js';

/**
 * 
 * @export
 * @interface OauthAuditPost200ResponseInner
 */
export interface OauthAuditPost200ResponseInner {
    /**
     * 
     * @type {string}
     * @memberof OauthAuditPost200ResponseInner
     */
    providerId: string;
    /**
     * 
     * @type {string}
     * @memberof OauthAuditPost200ResponseInner
     */
    providerDisplayName: string;
    /**
     * 
     * @type {string}
     * @memberof OauthAuditPost200ResponseInner
     */
    providerIcon: string;
    /**
     * 
     * @type {OauthAuditPost200ResponseInnerStatus}
     * @memberof OauthAuditPost200ResponseInner
     */
    status: OauthAuditPost200ResponseInnerStatus;
    /**
     * 
     * @type {Array<string>}
     * @memberof OauthAuditPost200ResponseInner
     */
    grantedCapabilities: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof OauthAuditPost200ResponseInner
     */
    missingCapabilities: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof OauthAuditPost200ResponseInner
     */
    oauthUrl: string;
    /**
     * 
     * @type {string}
     * @memberof OauthAuditPost200ResponseInner
     */
    message?: string;
}

/**
 * Check if a given object implements the OauthAuditPost200ResponseInner interface.
 */
export function instanceOfOauthAuditPost200ResponseInner(value: object): value is OauthAuditPost200ResponseInner {
    if (!('providerId' in value) || value['providerId'] === undefined) return false;
    if (!('providerDisplayName' in value) || value['providerDisplayName'] === undefined) return false;
    if (!('providerIcon' in value) || value['providerIcon'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('grantedCapabilities' in value) || value['grantedCapabilities'] === undefined) return false;
    if (!('missingCapabilities' in value) || value['missingCapabilities'] === undefined) return false;
    if (!('oauthUrl' in value) || value['oauthUrl'] === undefined) return false;
    return true;
}

export function OauthAuditPost200ResponseInnerFromJSON(json: any): OauthAuditPost200ResponseInner {
    return OauthAuditPost200ResponseInnerFromJSONTyped(json, false);
}

export function OauthAuditPost200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): OauthAuditPost200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'providerId': json['providerId'],
        'providerDisplayName': json['providerDisplayName'],
        'providerIcon': json['providerIcon'],
        'status': OauthAuditPost200ResponseInnerStatusFromJSON(json['status']),
        'grantedCapabilities': json['grantedCapabilities'],
        'missingCapabilities': json['missingCapabilities'],
        'oauthUrl': json['oauthUrl'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function OauthAuditPost200ResponseInnerToJSON(json: any): OauthAuditPost200ResponseInner {
    return OauthAuditPost200ResponseInnerToJSONTyped(json, false);
}

export function OauthAuditPost200ResponseInnerToJSONTyped(value?: OauthAuditPost200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'providerId': value['providerId'],
        'providerDisplayName': value['providerDisplayName'],
        'providerIcon': value['providerIcon'],
        'status': OauthAuditPost200ResponseInnerStatusToJSON(value['status']),
        'grantedCapabilities': value['grantedCapabilities'],
        'missingCapabilities': value['missingCapabilities'],
        'oauthUrl': value['oauthUrl'],
        'message': value['message'],
    };
}

