/* tslint:disable */
/* eslint-disable */
/**
 * ConnectHub API
 * Unified integration, token, and proxy layer for Clancy Digital-Employees
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OauthAuditPostRequestCapabilitiesInner } from './OauthAuditPostRequestCapabilitiesInner';
import {
    OauthAuditPostRequestCapabilitiesInnerFromJSON,
    OauthAuditPostRequestCapabilitiesInnerFromJSONTyped,
    OauthAuditPostRequestCapabilitiesInnerToJSON,
    OauthAuditPostRequestCapabilitiesInnerToJSONTyped,
} from './OauthAuditPostRequestCapabilitiesInner';
import type { OauthAuditPostRequestTriggersInner } from './OauthAuditPostRequestTriggersInner';
import {
    OauthAuditPostRequestTriggersInnerFromJSON,
    OauthAuditPostRequestTriggersInnerFromJSONTyped,
    OauthAuditPostRequestTriggersInnerToJSON,
    OauthAuditPostRequestTriggersInnerToJSONTyped,
} from './OauthAuditPostRequestTriggersInner';

/**
 * 
 * @export
 * @interface OauthAuditPostRequest
 */
export interface OauthAuditPostRequest {
    /**
     * 
     * @type {Array<OauthAuditPostRequestCapabilitiesInner>}
     * @memberof OauthAuditPostRequest
     */
    capabilities: Array<OauthAuditPostRequestCapabilitiesInner>;
    /**
     * 
     * @type {Array<OauthAuditPostRequestTriggersInner>}
     * @memberof OauthAuditPostRequest
     */
    triggers: Array<OauthAuditPostRequestTriggersInner>;
}

/**
 * Check if a given object implements the OauthAuditPostRequest interface.
 */
export function instanceOfOauthAuditPostRequest(value: object): value is OauthAuditPostRequest {
    if (!('capabilities' in value) || value['capabilities'] === undefined) return false;
    if (!('triggers' in value) || value['triggers'] === undefined) return false;
    return true;
}

export function OauthAuditPostRequestFromJSON(json: any): OauthAuditPostRequest {
    return OauthAuditPostRequestFromJSONTyped(json, false);
}

export function OauthAuditPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OauthAuditPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'capabilities': ((json['capabilities'] as Array<any>).map(OauthAuditPostRequestCapabilitiesInnerFromJSON)),
        'triggers': ((json['triggers'] as Array<any>).map(OauthAuditPostRequestTriggersInnerFromJSON)),
    };
}

export function OauthAuditPostRequestToJSON(json: any): OauthAuditPostRequest {
    return OauthAuditPostRequestToJSONTyped(json, false);
}

export function OauthAuditPostRequestToJSONTyped(value?: OauthAuditPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'capabilities': ((value['capabilities'] as Array<any>).map(OauthAuditPostRequestCapabilitiesInnerToJSON)),
        'triggers': ((value['triggers'] as Array<any>).map(OauthAuditPostRequestTriggersInnerToJSON)),
    };
}

