/* tslint:disable */
/* eslint-disable */
/**
 * ConnectHub API
 * Unified integration, token, and proxy layer for Clancy Digital-Employees
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ProviderKind = {
    Internal: 'internal',
    External: 'external'
} as const;
export type ProviderKind = typeof ProviderKind[keyof typeof ProviderKind];


export function instanceOfProviderKind(value: any): boolean {
    for (const key in ProviderKind) {
        if (Object.prototype.hasOwnProperty.call(ProviderKind, key)) {
            if (ProviderKind[key as keyof typeof ProviderKind] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ProviderKindFromJSON(json: any): ProviderKind {
    return ProviderKindFromJSONTyped(json, false);
}

export function ProviderKindFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProviderKind {
    return json as ProviderKind;
}

export function ProviderKindToJSON(value?: ProviderKind | null): any {
    return value as any;
}

export function ProviderKindToJSONTyped(value: any, ignoreDiscriminator: boolean): ProviderKind {
    return value as ProviderKind;
}

