/* tslint:disable */
/* eslint-disable */
/**
 * ConnectHub API
 * Unified integration, token, and proxy layer for Clancy Digital-Employees
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface TagsPostRequest
 */
export interface TagsPostRequest {
    /**
     * 
     * @type {string}
     * @memberof TagsPostRequest
     */
    name: string;
}

/**
 * Check if a given object implements the TagsPostRequest interface.
 */
export function instanceOfTagsPostRequest(value: object): value is TagsPostRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function TagsPostRequestFromJSON(json: any): TagsPostRequest {
    return TagsPostRequestFromJSONTyped(json, false);
}

export function TagsPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TagsPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function TagsPostRequestToJSON(json: any): TagsPostRequest {
    return TagsPostRequestToJSONTyped(json, false);
}

export function TagsPostRequestToJSONTyped(value?: TagsPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

