/* tslint:disable */
/* eslint-disable */
/**
 * ConnectHub API
 * Unified integration, token, and proxy layer for Clancy Digital-Employees
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Tag } from './Tag.js';
import {
    TagFromJSON,
    TagFromJSONTyped,
    TagToJSON,
    TagToJSONTyped,
} from './Tag.js';

/**
 * 
 * @export
 * @interface TagsGet200Response
 */
export interface TagsGet200Response {
    /**
     * 
     * @type {Array<Tag>}
     * @memberof TagsGet200Response
     */
    data: Array<Tag>;
    /**
     * 
     * @type {number}
     * @memberof TagsGet200Response
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof TagsGet200Response
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof TagsGet200Response
     */
    limit: number;
}

/**
 * Check if a given object implements the TagsGet200Response interface.
 */
export function instanceOfTagsGet200Response(value: object): value is TagsGet200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    return true;
}

export function TagsGet200ResponseFromJSON(json: any): TagsGet200Response {
    return TagsGet200ResponseFromJSONTyped(json, false);
}

export function TagsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TagsGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(TagFromJSON)),
        'total': json['total'],
        'page': json['page'],
        'limit': json['limit'],
    };
}

export function TagsGet200ResponseToJSON(json: any): TagsGet200Response {
    return TagsGet200ResponseToJSONTyped(json, false);
}

export function TagsGet200ResponseToJSONTyped(value?: TagsGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(TagToJSON)),
        'total': value['total'],
        'page': value['page'],
        'limit': value['limit'],
    };
}

