/* tslint:disable */
/* eslint-disable */
/**
 * ConnectHub API
 * Unified integration, token, and proxy layer for Clancy Digital-Employees
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface TagsPost200Response
 */
export interface TagsPost200Response {
    /**
     * 
     * @type {string}
     * @memberof TagsPost200Response
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof TagsPost200Response
     */
    orgId: string;
    /**
     * 
     * @type {string}
     * @memberof TagsPost200Response
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof TagsPost200Response
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof TagsPost200Response
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the TagsPost200Response interface.
 */
export function instanceOfTagsPost200Response(value: object): value is TagsPost200Response {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('orgId' in value) || value['orgId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function TagsPost200ResponseFromJSON(json: any): TagsPost200Response {
    return TagsPost200ResponseFromJSONTyped(json, false);
}

export function TagsPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TagsPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'orgId': json['orgId'],
        'name': json['name'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function TagsPost200ResponseToJSON(json: any): TagsPost200Response {
    return TagsPost200ResponseToJSONTyped(json, false);
}

export function TagsPost200ResponseToJSONTyped(value?: TagsPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'orgId': value['orgId'],
        'name': value['name'],
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': ((value['updatedAt']).toISOString()),
    };
}

