/* tslint:disable */
/* eslint-disable */
/**
 * ConnectHub API
 * Unified integration, token, and proxy layer for Clancy Digital-Employees
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface TriggersParamOptionsProviderIdTriggerIdGet200Response
 */
export interface TriggersParamOptionsProviderIdTriggerIdGet200Response {
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof TriggersParamOptionsProviderIdTriggerIdGet200Response
     */
    options: { [key: string]: any; };
}

/**
 * Check if a given object implements the TriggersParamOptionsProviderIdTriggerIdGet200Response interface.
 */
export function instanceOfTriggersParamOptionsProviderIdTriggerIdGet200Response(value: object): value is TriggersParamOptionsProviderIdTriggerIdGet200Response {
    if (!('options' in value) || value['options'] === undefined) return false;
    return true;
}

export function TriggersParamOptionsProviderIdTriggerIdGet200ResponseFromJSON(json: any): TriggersParamOptionsProviderIdTriggerIdGet200Response {
    return TriggersParamOptionsProviderIdTriggerIdGet200ResponseFromJSONTyped(json, false);
}

export function TriggersParamOptionsProviderIdTriggerIdGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TriggersParamOptionsProviderIdTriggerIdGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'options': json['options'],
    };
}

export function TriggersParamOptionsProviderIdTriggerIdGet200ResponseToJSON(json: any): TriggersParamOptionsProviderIdTriggerIdGet200Response {
    return TriggersParamOptionsProviderIdTriggerIdGet200ResponseToJSONTyped(json, false);
}

export function TriggersParamOptionsProviderIdTriggerIdGet200ResponseToJSONTyped(value?: TriggersParamOptionsProviderIdTriggerIdGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'options': value['options'],
    };
}

