/* tslint:disable */
/* eslint-disable */
/**
 * ConnectHub API
 * Unified integration, token, and proxy layer for Clancy Digital-Employees
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface TriggersParamOptionsGet200Response
 */
export interface TriggersParamOptionsGet200Response {
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof TriggersParamOptionsGet200Response
     */
    options: { [key: string]: any; };
}

/**
 * Check if a given object implements the TriggersParamOptionsGet200Response interface.
 */
export function instanceOfTriggersParamOptionsGet200Response(value: object): value is TriggersParamOptionsGet200Response {
    if (!('options' in value) || value['options'] === undefined) return false;
    return true;
}

export function TriggersParamOptionsGet200ResponseFromJSON(json: any): TriggersParamOptionsGet200Response {
    return TriggersParamOptionsGet200ResponseFromJSONTyped(json, false);
}

export function TriggersParamOptionsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TriggersParamOptionsGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'options': json['options'],
    };
}

export function TriggersParamOptionsGet200ResponseToJSON(json: any): TriggersParamOptionsGet200Response {
    return TriggersParamOptionsGet200ResponseToJSONTyped(json, false);
}

export function TriggersParamOptionsGet200ResponseToJSONTyped(value?: TriggersParamOptionsGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'options': value['options'],
    };
}

