/* tslint:disable */
/* eslint-disable */
/**
 * ConnectHub API
 * Unified integration, token, and proxy layer for Clancy Digital-Employees
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhooksInternalPostRequestAnyOf5Kind
 */
export interface WebhooksInternalPostRequestAnyOf5Kind {
}

/**
 * Check if a given object implements the WebhooksInternalPostRequestAnyOf5Kind interface.
 */
export function instanceOfWebhooksInternalPostRequestAnyOf5Kind(value: object): value is WebhooksInternalPostRequestAnyOf5Kind {
    return true;
}

export function WebhooksInternalPostRequestAnyOf5KindFromJSON(json: any): WebhooksInternalPostRequestAnyOf5Kind {
    return WebhooksInternalPostRequestAnyOf5KindFromJSONTyped(json, false);
}

export function WebhooksInternalPostRequestAnyOf5KindFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhooksInternalPostRequestAnyOf5Kind {
    return json;
}

export function WebhooksInternalPostRequestAnyOf5KindToJSON(json: any): WebhooksInternalPostRequestAnyOf5Kind {
    return WebhooksInternalPostRequestAnyOf5KindToJSONTyped(json, false);
}

export function WebhooksInternalPostRequestAnyOf5KindToJSONTyped(value?: WebhooksInternalPostRequestAnyOf5Kind | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

