/* tslint:disable */
/* eslint-disable */
/**
 * ConnectHub API
 * Unified integration, token, and proxy layer for Clancy Digital-Employees
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebhooksInternalPostRequestAnyOf3AgentsInnerWorkflow } from './WebhooksInternalPostRequestAnyOf3AgentsInnerWorkflow';
import {
    WebhooksInternalPostRequestAnyOf3AgentsInnerWorkflowFromJSON,
    WebhooksInternalPostRequestAnyOf3AgentsInnerWorkflowFromJSONTyped,
    WebhooksInternalPostRequestAnyOf3AgentsInnerWorkflowToJSON,
    WebhooksInternalPostRequestAnyOf3AgentsInnerWorkflowToJSONTyped,
} from './WebhooksInternalPostRequestAnyOf3AgentsInnerWorkflow';

/**
 * 
 * @export
 * @interface WebhooksInternalPostRequestAnyOf3AgentsInner
 */
export interface WebhooksInternalPostRequestAnyOf3AgentsInner {
    /**
     * 
     * @type {string}
     * @memberof WebhooksInternalPostRequestAnyOf3AgentsInner
     */
    prompt?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof WebhooksInternalPostRequestAnyOf3AgentsInner
     */
    capabilities: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof WebhooksInternalPostRequestAnyOf3AgentsInner
     */
    triggers: Array<string>;
    /**
     * 
     * @type {WebhooksInternalPostRequestAnyOf3AgentsInnerWorkflow}
     * @memberof WebhooksInternalPostRequestAnyOf3AgentsInner
     */
    workflow: WebhooksInternalPostRequestAnyOf3AgentsInnerWorkflow;
}

/**
 * Check if a given object implements the WebhooksInternalPostRequestAnyOf3AgentsInner interface.
 */
export function instanceOfWebhooksInternalPostRequestAnyOf3AgentsInner(value: object): value is WebhooksInternalPostRequestAnyOf3AgentsInner {
    if (!('capabilities' in value) || value['capabilities'] === undefined) return false;
    if (!('triggers' in value) || value['triggers'] === undefined) return false;
    if (!('workflow' in value) || value['workflow'] === undefined) return false;
    return true;
}

export function WebhooksInternalPostRequestAnyOf3AgentsInnerFromJSON(json: any): WebhooksInternalPostRequestAnyOf3AgentsInner {
    return WebhooksInternalPostRequestAnyOf3AgentsInnerFromJSONTyped(json, false);
}

export function WebhooksInternalPostRequestAnyOf3AgentsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhooksInternalPostRequestAnyOf3AgentsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'prompt': json['prompt'] == null ? undefined : json['prompt'],
        'capabilities': json['capabilities'],
        'triggers': json['triggers'],
        'workflow': WebhooksInternalPostRequestAnyOf3AgentsInnerWorkflowFromJSON(json['workflow']),
    };
}

export function WebhooksInternalPostRequestAnyOf3AgentsInnerToJSON(json: any): WebhooksInternalPostRequestAnyOf3AgentsInner {
    return WebhooksInternalPostRequestAnyOf3AgentsInnerToJSONTyped(json, false);
}

export function WebhooksInternalPostRequestAnyOf3AgentsInnerToJSONTyped(value?: WebhooksInternalPostRequestAnyOf3AgentsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'prompt': value['prompt'],
        'capabilities': value['capabilities'],
        'triggers': value['triggers'],
        'workflow': WebhooksInternalPostRequestAnyOf3AgentsInnerWorkflowToJSON(value['workflow']),
    };
}

