/* tslint:disable */
/* eslint-disable */
/**
 * ConnectHub API
 * Unified integration, token, and proxy layer for Clancy Digital-Employees
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface WebhooksSlackPostRequestOneOf1
 */
export interface WebhooksSlackPostRequestOneOf1 {
    /**
     * 
     * @type {string}
     * @memberof WebhooksSlackPostRequestOneOf1
     */
    token: string;
    /**
     * 
     * @type {string}
     * @memberof WebhooksSlackPostRequestOneOf1
     */
    type: WebhooksSlackPostRequestOneOf1TypeEnum;
    /**
     * 
     * @type {string}
     * @memberof WebhooksSlackPostRequestOneOf1
     */
    challenge: string;
}


/**
 * @export
 */
export const WebhooksSlackPostRequestOneOf1TypeEnum = {
    UrlVerification: 'url_verification'
} as const;
export type WebhooksSlackPostRequestOneOf1TypeEnum = typeof WebhooksSlackPostRequestOneOf1TypeEnum[keyof typeof WebhooksSlackPostRequestOneOf1TypeEnum];


/**
 * Check if a given object implements the WebhooksSlackPostRequestOneOf1 interface.
 */
export function instanceOfWebhooksSlackPostRequestOneOf1(value: object): value is WebhooksSlackPostRequestOneOf1 {
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('challenge' in value) || value['challenge'] === undefined) return false;
    return true;
}

export function WebhooksSlackPostRequestOneOf1FromJSON(json: any): WebhooksSlackPostRequestOneOf1 {
    return WebhooksSlackPostRequestOneOf1FromJSONTyped(json, false);
}

export function WebhooksSlackPostRequestOneOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhooksSlackPostRequestOneOf1 {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
        'type': json['type'],
        'challenge': json['challenge'],
    };
}

export function WebhooksSlackPostRequestOneOf1ToJSON(json: any): WebhooksSlackPostRequestOneOf1 {
    return WebhooksSlackPostRequestOneOf1ToJSONTyped(json, false);
}

export function WebhooksSlackPostRequestOneOf1ToJSONTyped(value?: WebhooksSlackPostRequestOneOf1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
        'type': value['type'],
        'challenge': value['challenge'],
    };
}

