/* tslint:disable */
/* eslint-disable */
/**
 * ConnectHub API
 * Unified integration, token, and proxy layer for Clancy Digital-Employees
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebhooksInternalPostRequestAnyOf5Kind } from './WebhooksInternalPostRequestAnyOf5Kind';
import {
    WebhooksInternalPostRequestAnyOf5KindFromJSON,
    WebhooksInternalPostRequestAnyOf5KindFromJSONTyped,
    WebhooksInternalPostRequestAnyOf5KindToJSON,
    WebhooksInternalPostRequestAnyOf5KindToJSONTyped,
} from './WebhooksInternalPostRequestAnyOf5Kind';

/**
 * 
 * @export
 * @interface WebhooksInternalPostRequestAnyOf6
 */
export interface WebhooksInternalPostRequestAnyOf6 {
    /**
     * 
     * @type {string}
     * @memberof WebhooksInternalPostRequestAnyOf6
     */
    type: WebhooksInternalPostRequestAnyOf6TypeEnum;
    /**
     * 
     * @type {string}
     * @memberof WebhooksInternalPostRequestAnyOf6
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof WebhooksInternalPostRequestAnyOf6
     */
    orgId: string;
    /**
     * 
     * @type {string}
     * @memberof WebhooksInternalPostRequestAnyOf6
     */
    timestamp: string;
    /**
     * 
     * @type {string}
     * @memberof WebhooksInternalPostRequestAnyOf6
     */
    executionId?: string;
    /**
     * 
     * @type {string}
     * @memberof WebhooksInternalPostRequestAnyOf6
     */
    promptId?: string;
    /**
     * 
     * @type {WebhooksInternalPostRequestAnyOf5Kind}
     * @memberof WebhooksInternalPostRequestAnyOf6
     */
    kind?: WebhooksInternalPostRequestAnyOf5Kind;
}


/**
 * @export
 */
export const WebhooksInternalPostRequestAnyOf6TypeEnum = {
    Humanfeedbackresponse: 'humanfeedbackresponse'
} as const;
export type WebhooksInternalPostRequestAnyOf6TypeEnum = typeof WebhooksInternalPostRequestAnyOf6TypeEnum[keyof typeof WebhooksInternalPostRequestAnyOf6TypeEnum];


/**
 * Check if a given object implements the WebhooksInternalPostRequestAnyOf6 interface.
 */
export function instanceOfWebhooksInternalPostRequestAnyOf6(value: object): value is WebhooksInternalPostRequestAnyOf6 {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('orgId' in value) || value['orgId'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function WebhooksInternalPostRequestAnyOf6FromJSON(json: any): WebhooksInternalPostRequestAnyOf6 {
    return WebhooksInternalPostRequestAnyOf6FromJSONTyped(json, false);
}

export function WebhooksInternalPostRequestAnyOf6FromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhooksInternalPostRequestAnyOf6 {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'userId': json['userId'],
        'orgId': json['orgId'],
        'timestamp': json['timestamp'],
        'executionId': json['executionId'] == null ? undefined : json['executionId'],
        'promptId': json['promptId'] == null ? undefined : json['promptId'],
        'kind': json['kind'] == null ? undefined : WebhooksInternalPostRequestAnyOf5KindFromJSON(json['kind']),
    };
}

export function WebhooksInternalPostRequestAnyOf6ToJSON(json: any): WebhooksInternalPostRequestAnyOf6 {
    return WebhooksInternalPostRequestAnyOf6ToJSONTyped(json, false);
}

export function WebhooksInternalPostRequestAnyOf6ToJSONTyped(value?: WebhooksInternalPostRequestAnyOf6 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'userId': value['userId'],
        'orgId': value['orgId'],
        'timestamp': value['timestamp'],
        'executionId': value['executionId'],
        'promptId': value['promptId'],
        'kind': WebhooksInternalPostRequestAnyOf5KindToJSON(value['kind']),
    };
}

