/* tslint:disable */
/* eslint-disable */
/**
 * ConnectHub API
 * Unified integration, token, and proxy layer for Clancy Digital-Employees
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebhooksInternalPostRequestAnyOf4ConnectionStatus } from './WebhooksInternalPostRequestAnyOf4ConnectionStatus';
import {
    WebhooksInternalPostRequestAnyOf4ConnectionStatusFromJSON,
    WebhooksInternalPostRequestAnyOf4ConnectionStatusFromJSONTyped,
    WebhooksInternalPostRequestAnyOf4ConnectionStatusToJSON,
    WebhooksInternalPostRequestAnyOf4ConnectionStatusToJSONTyped,
} from './WebhooksInternalPostRequestAnyOf4ConnectionStatus';

/**
 * 
 * @export
 * @interface WebhooksInternalPostRequestAnyOf4
 */
export interface WebhooksInternalPostRequestAnyOf4 {
    /**
     * 
     * @type {string}
     * @memberof WebhooksInternalPostRequestAnyOf4
     */
    type: WebhooksInternalPostRequestAnyOf4TypeEnum;
    /**
     * 
     * @type {string}
     * @memberof WebhooksInternalPostRequestAnyOf4
     */
    orgId: string;
    /**
     * 
     * @type {string}
     * @memberof WebhooksInternalPostRequestAnyOf4
     */
    timestamp: string;
    /**
     * 
     * @type {string}
     * @memberof WebhooksInternalPostRequestAnyOf4
     */
    providerId: string;
    /**
     * 
     * @type {WebhooksInternalPostRequestAnyOf4ConnectionStatus}
     * @memberof WebhooksInternalPostRequestAnyOf4
     */
    connectionStatus: WebhooksInternalPostRequestAnyOf4ConnectionStatus;
    /**
     * 
     * @type {string}
     * @memberof WebhooksInternalPostRequestAnyOf4
     */
    connectionId: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof WebhooksInternalPostRequestAnyOf4
     */
    externalAccountMetadata: { [key: string]: any; };
}


/**
 * @export
 */
export const WebhooksInternalPostRequestAnyOf4TypeEnum = {
    Providerconnectioncompleted: 'providerconnectioncompleted'
} as const;
export type WebhooksInternalPostRequestAnyOf4TypeEnum = typeof WebhooksInternalPostRequestAnyOf4TypeEnum[keyof typeof WebhooksInternalPostRequestAnyOf4TypeEnum];


/**
 * Check if a given object implements the WebhooksInternalPostRequestAnyOf4 interface.
 */
export function instanceOfWebhooksInternalPostRequestAnyOf4(value: object): value is WebhooksInternalPostRequestAnyOf4 {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('orgId' in value) || value['orgId'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('providerId' in value) || value['providerId'] === undefined) return false;
    if (!('connectionStatus' in value) || value['connectionStatus'] === undefined) return false;
    if (!('connectionId' in value) || value['connectionId'] === undefined) return false;
    if (!('externalAccountMetadata' in value) || value['externalAccountMetadata'] === undefined) return false;
    return true;
}

export function WebhooksInternalPostRequestAnyOf4FromJSON(json: any): WebhooksInternalPostRequestAnyOf4 {
    return WebhooksInternalPostRequestAnyOf4FromJSONTyped(json, false);
}

export function WebhooksInternalPostRequestAnyOf4FromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhooksInternalPostRequestAnyOf4 {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'orgId': json['orgId'],
        'timestamp': json['timestamp'],
        'providerId': json['providerId'],
        'connectionStatus': WebhooksInternalPostRequestAnyOf4ConnectionStatusFromJSON(json['connectionStatus']),
        'connectionId': json['connectionId'],
        'externalAccountMetadata': json['externalAccountMetadata'],
    };
}

export function WebhooksInternalPostRequestAnyOf4ToJSON(json: any): WebhooksInternalPostRequestAnyOf4 {
    return WebhooksInternalPostRequestAnyOf4ToJSONTyped(json, false);
}

export function WebhooksInternalPostRequestAnyOf4ToJSONTyped(value?: WebhooksInternalPostRequestAnyOf4 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'orgId': value['orgId'],
        'timestamp': value['timestamp'],
        'providerId': value['providerId'],
        'connectionStatus': WebhooksInternalPostRequestAnyOf4ConnectionStatusToJSON(value['connectionStatus']),
        'connectionId': value['connectionId'],
        'externalAccountMetadata': value['externalAccountMetadata'],
    };
}

