/* tslint:disable */
/* eslint-disable */
/**
 * ConnectHub API
 * Unified integration, token, and proxy layer for Clancy Digital-Employees
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhooksInternalPostRequestAnyOf7
 */
export interface WebhooksInternalPostRequestAnyOf7 {
    /**
     * 
     * @type {string}
     * @memberof WebhooksInternalPostRequestAnyOf7
     */
    type: WebhooksInternalPostRequestAnyOf7TypeEnum;
    /**
     * 
     * @type {string}
     * @memberof WebhooksInternalPostRequestAnyOf7
     */
    orgId: string;
    /**
     * 
     * @type {string}
     * @memberof WebhooksInternalPostRequestAnyOf7
     */
    timestamp: string;
    /**
     * 
     * @type {string}
     * @memberof WebhooksInternalPostRequestAnyOf7
     */
    agentId: string;
    /**
     * 
     * @type {string}
     * @memberof WebhooksInternalPostRequestAnyOf7
     */
    executionId: string;
    /**
     * 
     * @type {string}
     * @memberof WebhooksInternalPostRequestAnyOf7
     */
    model: string;
    /**
     * 
     * @type {number}
     * @memberof WebhooksInternalPostRequestAnyOf7
     */
    promptTokens: number;
    /**
     * 
     * @type {number}
     * @memberof WebhooksInternalPostRequestAnyOf7
     */
    completionTokens: number;
    /**
     * 
     * @type {number}
     * @memberof WebhooksInternalPostRequestAnyOf7
     */
    totalTokens: number;
    /**
     * 
     * @type {string}
     * @memberof WebhooksInternalPostRequestAnyOf7
     */
    prompt: string;
}


/**
 * @export
 */
export const WebhooksInternalPostRequestAnyOf7TypeEnum = {
    Llmusage: 'llmusage'
} as const;
export type WebhooksInternalPostRequestAnyOf7TypeEnum = typeof WebhooksInternalPostRequestAnyOf7TypeEnum[keyof typeof WebhooksInternalPostRequestAnyOf7TypeEnum];


/**
 * Check if a given object implements the WebhooksInternalPostRequestAnyOf7 interface.
 */
export function instanceOfWebhooksInternalPostRequestAnyOf7(value: object): value is WebhooksInternalPostRequestAnyOf7 {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('orgId' in value) || value['orgId'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('agentId' in value) || value['agentId'] === undefined) return false;
    if (!('executionId' in value) || value['executionId'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('promptTokens' in value) || value['promptTokens'] === undefined) return false;
    if (!('completionTokens' in value) || value['completionTokens'] === undefined) return false;
    if (!('totalTokens' in value) || value['totalTokens'] === undefined) return false;
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    return true;
}

export function WebhooksInternalPostRequestAnyOf7FromJSON(json: any): WebhooksInternalPostRequestAnyOf7 {
    return WebhooksInternalPostRequestAnyOf7FromJSONTyped(json, false);
}

export function WebhooksInternalPostRequestAnyOf7FromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhooksInternalPostRequestAnyOf7 {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'orgId': json['orgId'],
        'timestamp': json['timestamp'],
        'agentId': json['agentId'],
        'executionId': json['executionId'],
        'model': json['model'],
        'promptTokens': json['promptTokens'],
        'completionTokens': json['completionTokens'],
        'totalTokens': json['totalTokens'],
        'prompt': json['prompt'],
    };
}

export function WebhooksInternalPostRequestAnyOf7ToJSON(json: any): WebhooksInternalPostRequestAnyOf7 {
    return WebhooksInternalPostRequestAnyOf7ToJSONTyped(json, false);
}

export function WebhooksInternalPostRequestAnyOf7ToJSONTyped(value?: WebhooksInternalPostRequestAnyOf7 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'orgId': value['orgId'],
        'timestamp': value['timestamp'],
        'agentId': value['agentId'],
        'executionId': value['executionId'],
        'model': value['model'],
        'promptTokens': value['promptTokens'],
        'completionTokens': value['completionTokens'],
        'totalTokens': value['totalTokens'],
        'prompt': value['prompt'],
    };
}

