/* tslint:disable */
/* eslint-disable */
/**
 * ConnectHub API
 * Unified integration, token, and proxy layer for Clancy Digital-Employees
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhooksSlackPostRequestOneOfEvent
 */
export interface WebhooksSlackPostRequestOneOfEvent {
    /**
     * 
     * @type {string}
     * @memberof WebhooksSlackPostRequestOneOfEvent
     */
    type: string;
}

/**
 * Check if a given object implements the WebhooksSlackPostRequestOneOfEvent interface.
 */
export function instanceOfWebhooksSlackPostRequestOneOfEvent(value: object): value is WebhooksSlackPostRequestOneOfEvent {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function WebhooksSlackPostRequestOneOfEventFromJSON(json: any): WebhooksSlackPostRequestOneOfEvent {
    return WebhooksSlackPostRequestOneOfEventFromJSONTyped(json, false);
}

export function WebhooksSlackPostRequestOneOfEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhooksSlackPostRequestOneOfEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
    };
}

export function WebhooksSlackPostRequestOneOfEventToJSON(json: any): WebhooksSlackPostRequestOneOfEvent {
    return WebhooksSlackPostRequestOneOfEventToJSONTyped(json, false);
}

export function WebhooksSlackPostRequestOneOfEventToJSONTyped(value?: WebhooksSlackPostRequestOneOfEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
    };
}

