/* tslint:disable */
/* eslint-disable */
/**
 * ConnectHub API
 * Unified integration, token, and proxy layer for Clancy Digital-Employees
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhooksInternalPostRequestAnyOf3AgentsInnerWorkflow
 */
export interface WebhooksInternalPostRequestAnyOf3AgentsInnerWorkflow {
    /**
     * 
     * @type {string}
     * @memberof WebhooksInternalPostRequestAnyOf3AgentsInnerWorkflow
     */
    description: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof WebhooksInternalPostRequestAnyOf3AgentsInnerWorkflow
     */
    steps: Array<string>;
}

/**
 * Check if a given object implements the WebhooksInternalPostRequestAnyOf3AgentsInnerWorkflow interface.
 */
export function instanceOfWebhooksInternalPostRequestAnyOf3AgentsInnerWorkflow(value: object): value is WebhooksInternalPostRequestAnyOf3AgentsInnerWorkflow {
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('steps' in value) || value['steps'] === undefined) return false;
    return true;
}

export function WebhooksInternalPostRequestAnyOf3AgentsInnerWorkflowFromJSON(json: any): WebhooksInternalPostRequestAnyOf3AgentsInnerWorkflow {
    return WebhooksInternalPostRequestAnyOf3AgentsInnerWorkflowFromJSONTyped(json, false);
}

export function WebhooksInternalPostRequestAnyOf3AgentsInnerWorkflowFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhooksInternalPostRequestAnyOf3AgentsInnerWorkflow {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'],
        'steps': json['steps'],
    };
}

export function WebhooksInternalPostRequestAnyOf3AgentsInnerWorkflowToJSON(json: any): WebhooksInternalPostRequestAnyOf3AgentsInnerWorkflow {
    return WebhooksInternalPostRequestAnyOf3AgentsInnerWorkflowToJSONTyped(json, false);
}

export function WebhooksInternalPostRequestAnyOf3AgentsInnerWorkflowToJSONTyped(value?: WebhooksInternalPostRequestAnyOf3AgentsInnerWorkflow | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'steps': value['steps'],
    };
}

