/* tslint:disable */
/* eslint-disable */
/**
 * ConnectHub API
 * Unified integration, token, and proxy layer for Clancy Digital-Employees
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhooksInternalPostRequestAnyOf5RequestOneOf
 */
export interface WebhooksInternalPostRequestAnyOf5RequestOneOf {
    /**
     * 
     * @type {string}
     * @memberof WebhooksInternalPostRequestAnyOf5RequestOneOf
     */
    type: WebhooksInternalPostRequestAnyOf5RequestOneOfTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof WebhooksInternalPostRequestAnyOf5RequestOneOf
     */
    text: string;
}


/**
 * @export
 */
export const WebhooksInternalPostRequestAnyOf5RequestOneOfTypeEnum = {
    Text: 'text'
} as const;
export type WebhooksInternalPostRequestAnyOf5RequestOneOfTypeEnum = typeof WebhooksInternalPostRequestAnyOf5RequestOneOfTypeEnum[keyof typeof WebhooksInternalPostRequestAnyOf5RequestOneOfTypeEnum];


/**
 * Check if a given object implements the WebhooksInternalPostRequestAnyOf5RequestOneOf interface.
 */
export function instanceOfWebhooksInternalPostRequestAnyOf5RequestOneOf(value: object): value is WebhooksInternalPostRequestAnyOf5RequestOneOf {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function WebhooksInternalPostRequestAnyOf5RequestOneOfFromJSON(json: any): WebhooksInternalPostRequestAnyOf5RequestOneOf {
    return WebhooksInternalPostRequestAnyOf5RequestOneOfFromJSONTyped(json, false);
}

export function WebhooksInternalPostRequestAnyOf5RequestOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhooksInternalPostRequestAnyOf5RequestOneOf {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'text': json['text'],
    };
}

export function WebhooksInternalPostRequestAnyOf5RequestOneOfToJSON(json: any): WebhooksInternalPostRequestAnyOf5RequestOneOf {
    return WebhooksInternalPostRequestAnyOf5RequestOneOfToJSONTyped(json, false);
}

export function WebhooksInternalPostRequestAnyOf5RequestOneOfToJSONTyped(value?: WebhooksInternalPostRequestAnyOf5RequestOneOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'text': value['text'],
    };
}

