/* tslint:disable */
/* eslint-disable */
/**
 * Agent-Core API
 * Agent-Core Service - Control plane for multi-agent workflow orchestration
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AgentRunStatus = {
    Running: 'running',
    Completed: 'completed',
    Failed: 'failed'
} as const;
export type AgentRunStatus = typeof AgentRunStatus[keyof typeof AgentRunStatus];


export function instanceOfAgentRunStatus(value: any): boolean {
    for (const key in AgentRunStatus) {
        if (Object.prototype.hasOwnProperty.call(AgentRunStatus, key)) {
            if (AgentRunStatus[key as keyof typeof AgentRunStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AgentRunStatusFromJSON(json: any): AgentRunStatus {
    return AgentRunStatusFromJSONTyped(json, false);
}

export function AgentRunStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentRunStatus {
    return json as AgentRunStatus;
}

export function AgentRunStatusToJSON(value?: AgentRunStatus | null): any {
    return value as any;
}

export function AgentRunStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): AgentRunStatus {
    return value as AgentRunStatus;
}

