/* tslint:disable */
/* eslint-disable */
/**
 * Agent-Core API
 * Agent-Core Service - Control plane for multi-agent workflow orchestration
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApprovalRequest
 */
export interface ApprovalRequest {
    /**
     * 
     * @type {string}
     * @memberof ApprovalRequest
     */
    readonly id?: string;
    /**
     * 
     * @type {string}
     * @memberof ApprovalRequest
     */
    agentId: string;
    /**
     * 
     * @type {string}
     * @memberof ApprovalRequest
     */
    runId: string;
    /**
     * 
     * @type {string}
     * @memberof ApprovalRequest
     */
    status?: ApprovalRequestStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ApprovalRequest
     */
    summary: string;
    /**
     * 
     * @type {object}
     * @memberof ApprovalRequest
     */
    modifications: object;
    /**
     * 
     * @type {string}
     * @memberof ApprovalRequest
     */
    capability: string;
    /**
     * 
     * @type {object}
     * @memberof ApprovalRequest
     */
    request: object;
    /**
     * 
     * @type {string}
     * @memberof ApprovalRequest
     */
    readonly createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ApprovalRequest
     */
    readonly updatedAt?: string;
}


/**
 * @export
 */
export const ApprovalRequestStatusEnum = {
    Pending: 'pending',
    Approved: 'approved',
    Rejected: 'rejected'
} as const;
export type ApprovalRequestStatusEnum = typeof ApprovalRequestStatusEnum[keyof typeof ApprovalRequestStatusEnum];


/**
 * Check if a given object implements the ApprovalRequest interface.
 */
export function instanceOfApprovalRequest(value: object): value is ApprovalRequest {
    if (!('agentId' in value) || value['agentId'] === undefined) return false;
    if (!('runId' in value) || value['runId'] === undefined) return false;
    if (!('summary' in value) || value['summary'] === undefined) return false;
    if (!('modifications' in value) || value['modifications'] === undefined) return false;
    if (!('capability' in value) || value['capability'] === undefined) return false;
    if (!('request' in value) || value['request'] === undefined) return false;
    return true;
}

export function ApprovalRequestFromJSON(json: any): ApprovalRequest {
    return ApprovalRequestFromJSONTyped(json, false);
}

export function ApprovalRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApprovalRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'agentId': json['agentId'],
        'runId': json['runId'],
        'status': json['status'] == null ? undefined : json['status'],
        'summary': json['summary'],
        'modifications': json['modifications'],
        'capability': json['capability'],
        'request': json['request'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'updatedAt': json['updatedAt'] == null ? undefined : json['updatedAt'],
    };
}

export function ApprovalRequestToJSON(json: any): ApprovalRequest {
    return ApprovalRequestToJSONTyped(json, false);
}

export function ApprovalRequestToJSONTyped(value?: Omit<ApprovalRequest, 'id'|'createdAt'|'updatedAt'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'agentId': value['agentId'],
        'runId': value['runId'],
        'status': value['status'],
        'summary': value['summary'],
        'modifications': value['modifications'],
        'capability': value['capability'],
        'request': value['request'],
    };
}

