/* tslint:disable */
/* eslint-disable */
/**
 * Agent-Core API
 * Agent-Core Service - Control plane for multi-agent workflow orchestration
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { TemplateStatus } from './TemplateStatus.js';
import {
    TemplateStatusFromJSON,
    TemplateStatusFromJSONTyped,
    TemplateStatusToJSON,
    TemplateStatusToJSONTyped,
} from './TemplateStatus.js';

/**
 * 
 * @export
 * @interface PublicTemplatesGet200ResponseInner
 */
export interface PublicTemplatesGet200ResponseInner {
    /**
     * 
     * @type {string}
     * @memberof PublicTemplatesGet200ResponseInner
     */
    id: string;
    /**
     * 
     * @type {TemplateStatus}
     * @memberof PublicTemplatesGet200ResponseInner
     */
    status: TemplateStatus;
    /**
     * 
     * @type {string}
     * @memberof PublicTemplatesGet200ResponseInner
     */
    headline: string;
    /**
     * 
     * @type {string}
     * @memberof PublicTemplatesGet200ResponseInner
     */
    promise: string;
    /**
     * 
     * @type {string}
     * @memberof PublicTemplatesGet200ResponseInner
     */
    category: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof PublicTemplatesGet200ResponseInner
     */
    integrations: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof PublicTemplatesGet200ResponseInner
     */
    jdSeed: string;
    /**
     * 
     * @type {string}
     * @memberof PublicTemplatesGet200ResponseInner
     */
    icon: string;
}



/**
 * Check if a given object implements the PublicTemplatesGet200ResponseInner interface.
 */
export function instanceOfPublicTemplatesGet200ResponseInner(value: object): value is PublicTemplatesGet200ResponseInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('headline' in value) || value['headline'] === undefined) return false;
    if (!('promise' in value) || value['promise'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('integrations' in value) || value['integrations'] === undefined) return false;
    if (!('jdSeed' in value) || value['jdSeed'] === undefined) return false;
    if (!('icon' in value) || value['icon'] === undefined) return false;
    return true;
}

export function PublicTemplatesGet200ResponseInnerFromJSON(json: any): PublicTemplatesGet200ResponseInner {
    return PublicTemplatesGet200ResponseInnerFromJSONTyped(json, false);
}

export function PublicTemplatesGet200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicTemplatesGet200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': TemplateStatusFromJSON(json['status']),
        'headline': json['headline'],
        'promise': json['promise'],
        'category': json['category'],
        'integrations': json['integrations'],
        'jdSeed': json['jdSeed'],
        'icon': json['icon'],
    };
}

export function PublicTemplatesGet200ResponseInnerToJSON(json: any): PublicTemplatesGet200ResponseInner {
    return PublicTemplatesGet200ResponseInnerToJSONTyped(json, false);
}

export function PublicTemplatesGet200ResponseInnerToJSONTyped(value?: PublicTemplatesGet200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': TemplateStatusToJSON(value['status']),
        'headline': value['headline'],
        'promise': value['promise'],
        'category': value['category'],
        'integrations': value['integrations'],
        'jdSeed': value['jdSeed'],
        'icon': value['icon'],
    };
}

