/* tslint:disable */
/* eslint-disable */
/**
 * Agent-Core API
 * Agent-Core Service - Control plane for multi-agent workflow orchestration
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const TemplateStatus = {
    Active: 'active',
    Inactive: 'inactive'
} as const;
export type TemplateStatus = typeof TemplateStatus[keyof typeof TemplateStatus];


export function instanceOfTemplateStatus(value: any): boolean {
    for (const key in TemplateStatus) {
        if (Object.prototype.hasOwnProperty.call(TemplateStatus, key)) {
            if (TemplateStatus[key as keyof typeof TemplateStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TemplateStatusFromJSON(json: any): TemplateStatus {
    return TemplateStatusFromJSONTyped(json, false);
}

export function TemplateStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplateStatus {
    return json as TemplateStatus;
}

export function TemplateStatusToJSON(value?: TemplateStatus | null): any {
    return value as any;
}

export function TemplateStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): TemplateStatus {
    return value as TemplateStatus;
}

