/* tslint:disable */
/* eslint-disable */
/**
 * Agent-Core API
 * Agent-Core Service - Control plane for multi-agent workflow orchestration
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { TemplateStatus } from './TemplateStatus.js';
import {
    TemplateStatusFromJSON,
    TemplateStatusFromJSONTyped,
    TemplateStatusToJSON,
    TemplateStatusToJSONTyped,
} from './TemplateStatus.js';

/**
 * 
 * @export
 * @interface TemplatePublic
 */
export interface TemplatePublic {
    /**
     * 
     * @type {string}
     * @memberof TemplatePublic
     */
    id: string;
    /**
     * 
     * @type {TemplateStatus}
     * @memberof TemplatePublic
     */
    status: TemplateStatus;
    /**
     * 
     * @type {string}
     * @memberof TemplatePublic
     */
    headline: string;
    /**
     * 
     * @type {string}
     * @memberof TemplatePublic
     */
    promise: string;
    /**
     * 
     * @type {string}
     * @memberof TemplatePublic
     */
    category: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof TemplatePublic
     */
    integrations: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof TemplatePublic
     */
    jdSeed: string;
    /**
     * 
     * @type {string}
     * @memberof TemplatePublic
     */
    icon: string;
}



/**
 * Check if a given object implements the TemplatePublic interface.
 */
export function instanceOfTemplatePublic(value: object): value is TemplatePublic {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('headline' in value) || value['headline'] === undefined) return false;
    if (!('promise' in value) || value['promise'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('integrations' in value) || value['integrations'] === undefined) return false;
    if (!('jdSeed' in value) || value['jdSeed'] === undefined) return false;
    if (!('icon' in value) || value['icon'] === undefined) return false;
    return true;
}

export function TemplatePublicFromJSON(json: any): TemplatePublic {
    return TemplatePublicFromJSONTyped(json, false);
}

export function TemplatePublicFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatePublic {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': TemplateStatusFromJSON(json['status']),
        'headline': json['headline'],
        'promise': json['promise'],
        'category': json['category'],
        'integrations': json['integrations'],
        'jdSeed': json['jdSeed'],
        'icon': json['icon'],
    };
}

export function TemplatePublicToJSON(json: any): TemplatePublic {
    return TemplatePublicToJSONTyped(json, false);
}

export function TemplatePublicToJSONTyped(value?: TemplatePublic | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': TemplateStatusToJSON(value['status']),
        'headline': value['headline'],
        'promise': value['promise'],
        'category': value['category'],
        'integrations': value['integrations'],
        'jdSeed': value['jdSeed'],
        'icon': value['icon'],
    };
}

