/* tslint:disable */
/* eslint-disable */
/**
 * Agent-Core API
 * Agent-Core Service - Control plane for multi-agent workflow orchestration
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1AgentsIdPutRequestCapabilitiesInner
 */
export interface V1AgentsIdPutRequestCapabilitiesInner {
    /**
     * 
     * @type {string}
     * @memberof V1AgentsIdPutRequestCapabilitiesInner
     */
    providerId: string;
    /**
     * 
     * @type {string}
     * @memberof V1AgentsIdPutRequestCapabilitiesInner
     */
    id: string;
}

/**
 * Check if a given object implements the V1AgentsIdPutRequestCapabilitiesInner interface.
 */
export function instanceOfV1AgentsIdPutRequestCapabilitiesInner(value: object): value is V1AgentsIdPutRequestCapabilitiesInner {
    if (!('providerId' in value) || value['providerId'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function V1AgentsIdPutRequestCapabilitiesInnerFromJSON(json: any): V1AgentsIdPutRequestCapabilitiesInner {
    return V1AgentsIdPutRequestCapabilitiesInnerFromJSONTyped(json, false);
}

export function V1AgentsIdPutRequestCapabilitiesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1AgentsIdPutRequestCapabilitiesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'providerId': json['providerId'],
        'id': json['id'],
    };
}

export function V1AgentsIdPutRequestCapabilitiesInnerToJSON(json: any): V1AgentsIdPutRequestCapabilitiesInner {
    return V1AgentsIdPutRequestCapabilitiesInnerToJSONTyped(json, false);
}

export function V1AgentsIdPutRequestCapabilitiesInnerToJSONTyped(value?: V1AgentsIdPutRequestCapabilitiesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'providerId': value['providerId'],
        'id': value['id'],
    };
}

