/* tslint:disable */
/* eslint-disable */
/**
 * Agent-Core API
 * Agent-Core Service - Control plane for multi-agent workflow orchestration
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface V1ApprovalsIdPutRequest
 */
export interface V1ApprovalsIdPutRequest {
    /**
     * 
     * @type {string}
     * @memberof V1ApprovalsIdPutRequest
     */
    status?: V1ApprovalsIdPutRequestStatusEnum;
    /**
     * 
     * @type {object}
     * @memberof V1ApprovalsIdPutRequest
     */
    modifications?: object;
}


/**
 * @export
 */
export const V1ApprovalsIdPutRequestStatusEnum = {
    Pending: 'pending',
    Approved: 'approved',
    Rejected: 'rejected'
} as const;
export type V1ApprovalsIdPutRequestStatusEnum = typeof V1ApprovalsIdPutRequestStatusEnum[keyof typeof V1ApprovalsIdPutRequestStatusEnum];


/**
 * Check if a given object implements the V1ApprovalsIdPutRequest interface.
 */
export function instanceOfV1ApprovalsIdPutRequest(value: object): value is V1ApprovalsIdPutRequest {
    return true;
}

export function V1ApprovalsIdPutRequestFromJSON(json: any): V1ApprovalsIdPutRequest {
    return V1ApprovalsIdPutRequestFromJSONTyped(json, false);
}

export function V1ApprovalsIdPutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ApprovalsIdPutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'modifications': json['modifications'] == null ? undefined : json['modifications'],
    };
}

export function V1ApprovalsIdPutRequestToJSON(json: any): V1ApprovalsIdPutRequest {
    return V1ApprovalsIdPutRequestToJSONTyped(json, false);
}

export function V1ApprovalsIdPutRequestToJSONTyped(value?: V1ApprovalsIdPutRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'modifications': value['modifications'],
    };
}

