/* tslint:disable */
/* eslint-disable */
/**
 * Agent-Core API
 * Agent-Core Service - Control plane for multi-agent workflow orchestration
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhookPostRequestAnyOf7RequestAnyOf
 */
export interface WebhookPostRequestAnyOf7RequestAnyOf {
    /**
     * 
     * @type {string}
     * @memberof WebhookPostRequestAnyOf7RequestAnyOf
     */
    type: WebhookPostRequestAnyOf7RequestAnyOfTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof WebhookPostRequestAnyOf7RequestAnyOf
     */
    text: string;
}


/**
 * @export
 */
export const WebhookPostRequestAnyOf7RequestAnyOfTypeEnum = {
    Text: 'text'
} as const;
export type WebhookPostRequestAnyOf7RequestAnyOfTypeEnum = typeof WebhookPostRequestAnyOf7RequestAnyOfTypeEnum[keyof typeof WebhookPostRequestAnyOf7RequestAnyOfTypeEnum];


/**
 * Check if a given object implements the WebhookPostRequestAnyOf7RequestAnyOf interface.
 */
export function instanceOfWebhookPostRequestAnyOf7RequestAnyOf(value: object): value is WebhookPostRequestAnyOf7RequestAnyOf {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function WebhookPostRequestAnyOf7RequestAnyOfFromJSON(json: any): WebhookPostRequestAnyOf7RequestAnyOf {
    return WebhookPostRequestAnyOf7RequestAnyOfFromJSONTyped(json, false);
}

export function WebhookPostRequestAnyOf7RequestAnyOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookPostRequestAnyOf7RequestAnyOf {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'text': json['text'],
    };
}

export function WebhookPostRequestAnyOf7RequestAnyOfToJSON(json: any): WebhookPostRequestAnyOf7RequestAnyOf {
    return WebhookPostRequestAnyOf7RequestAnyOfToJSONTyped(json, false);
}

export function WebhookPostRequestAnyOf7RequestAnyOfToJSONTyped(value?: WebhookPostRequestAnyOf7RequestAnyOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'text': value['text'],
    };
}

