/* tslint:disable */
/* eslint-disable */
/**
 * Agent-Core API
 * Agent-Core Service - Control plane for multi-agent workflow orchestration
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhookPostRequestAnyOf3AgentsInnerTrigger
 */
export interface WebhookPostRequestAnyOf3AgentsInnerTrigger {
    /**
     * 
     * @type {string}
     * @memberof WebhookPostRequestAnyOf3AgentsInnerTrigger
     */
    providerId: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookPostRequestAnyOf3AgentsInnerTrigger
     */
    id: string;
    /**
     * Parameters for the trigger in the format specified by the get_triggers tool.
     * @type {any}
     * @memberof WebhookPostRequestAnyOf3AgentsInnerTrigger
     */
    triggerParams: any | null;
}

/**
 * Check if a given object implements the WebhookPostRequestAnyOf3AgentsInnerTrigger interface.
 */
export function instanceOfWebhookPostRequestAnyOf3AgentsInnerTrigger(value: object): value is WebhookPostRequestAnyOf3AgentsInnerTrigger {
    if (!('providerId' in value) || value['providerId'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('triggerParams' in value) || value['triggerParams'] === undefined) return false;
    return true;
}

export function WebhookPostRequestAnyOf3AgentsInnerTriggerFromJSON(json: any): WebhookPostRequestAnyOf3AgentsInnerTrigger {
    return WebhookPostRequestAnyOf3AgentsInnerTriggerFromJSONTyped(json, false);
}

export function WebhookPostRequestAnyOf3AgentsInnerTriggerFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookPostRequestAnyOf3AgentsInnerTrigger {
    if (json == null) {
        return json;
    }
    return {
        
        'providerId': json['providerId'],
        'id': json['id'],
        'triggerParams': json['triggerParams'],
    };
}

export function WebhookPostRequestAnyOf3AgentsInnerTriggerToJSON(json: any): WebhookPostRequestAnyOf3AgentsInnerTrigger {
    return WebhookPostRequestAnyOf3AgentsInnerTriggerToJSONTyped(json, false);
}

export function WebhookPostRequestAnyOf3AgentsInnerTriggerToJSONTyped(value?: WebhookPostRequestAnyOf3AgentsInnerTrigger | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'providerId': value['providerId'],
        'id': value['id'],
        'triggerParams': value['triggerParams'],
    };
}

