/* tslint:disable */
/* eslint-disable */
/**
 * Agent-Core API
 * Agent-Core Service - Control plane for multi-agent workflow orchestration
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebhookPostRequestAnyOf3AgentsInnerWorkflow } from './WebhookPostRequestAnyOf3AgentsInnerWorkflow';
import {
    WebhookPostRequestAnyOf3AgentsInnerWorkflowFromJSON,
    WebhookPostRequestAnyOf3AgentsInnerWorkflowFromJSONTyped,
    WebhookPostRequestAnyOf3AgentsInnerWorkflowToJSON,
    WebhookPostRequestAnyOf3AgentsInnerWorkflowToJSONTyped,
} from './WebhookPostRequestAnyOf3AgentsInnerWorkflow';

/**
 * 
 * @export
 * @interface WebhookPostRequestAnyOf3AgentsInner
 */
export interface WebhookPostRequestAnyOf3AgentsInner {
    /**
     * 
     * @type {string}
     * @memberof WebhookPostRequestAnyOf3AgentsInner
     */
    prompt?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof WebhookPostRequestAnyOf3AgentsInner
     */
    capabilities: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof WebhookPostRequestAnyOf3AgentsInner
     */
    triggers: Array<string>;
    /**
     * 
     * @type {WebhookPostRequestAnyOf3AgentsInnerWorkflow}
     * @memberof WebhookPostRequestAnyOf3AgentsInner
     */
    workflow: WebhookPostRequestAnyOf3AgentsInnerWorkflow;
}

/**
 * Check if a given object implements the WebhookPostRequestAnyOf3AgentsInner interface.
 */
export function instanceOfWebhookPostRequestAnyOf3AgentsInner(value: object): value is WebhookPostRequestAnyOf3AgentsInner {
    if (!('capabilities' in value) || value['capabilities'] === undefined) return false;
    if (!('triggers' in value) || value['triggers'] === undefined) return false;
    if (!('workflow' in value) || value['workflow'] === undefined) return false;
    return true;
}

export function WebhookPostRequestAnyOf3AgentsInnerFromJSON(json: any): WebhookPostRequestAnyOf3AgentsInner {
    return WebhookPostRequestAnyOf3AgentsInnerFromJSONTyped(json, false);
}

export function WebhookPostRequestAnyOf3AgentsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookPostRequestAnyOf3AgentsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'prompt': json['prompt'] == null ? undefined : json['prompt'],
        'capabilities': json['capabilities'],
        'triggers': json['triggers'],
        'workflow': WebhookPostRequestAnyOf3AgentsInnerWorkflowFromJSON(json['workflow']),
    };
}

export function WebhookPostRequestAnyOf3AgentsInnerToJSON(json: any): WebhookPostRequestAnyOf3AgentsInner {
    return WebhookPostRequestAnyOf3AgentsInnerToJSONTyped(json, false);
}

export function WebhookPostRequestAnyOf3AgentsInnerToJSONTyped(value?: WebhookPostRequestAnyOf3AgentsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'prompt': value['prompt'],
        'capabilities': value['capabilities'],
        'triggers': value['triggers'],
        'workflow': WebhookPostRequestAnyOf3AgentsInnerWorkflowToJSON(value['workflow']),
    };
}

