/* tslint:disable */
/* eslint-disable */
/**
 * Agent-Core API
 * Agent-Core Service - Control plane for multi-agent workflow orchestration
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface WebhookPostRequestAnyOf1ConnectionStatus
 */
export interface WebhookPostRequestAnyOf1ConnectionStatus {
}

/**
 * Check if a given object implements the WebhookPostRequestAnyOf1ConnectionStatus interface.
 */
export function instanceOfWebhookPostRequestAnyOf1ConnectionStatus(value: object): value is WebhookPostRequestAnyOf1ConnectionStatus {
    return true;
}

export function WebhookPostRequestAnyOf1ConnectionStatusFromJSON(json: any): WebhookPostRequestAnyOf1ConnectionStatus {
    return WebhookPostRequestAnyOf1ConnectionStatusFromJSONTyped(json, false);
}

export function WebhookPostRequestAnyOf1ConnectionStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookPostRequestAnyOf1ConnectionStatus {
    return json;
}

export function WebhookPostRequestAnyOf1ConnectionStatusToJSON(json: any): WebhookPostRequestAnyOf1ConnectionStatus {
    return WebhookPostRequestAnyOf1ConnectionStatusToJSONTyped(json, false);
}

export function WebhookPostRequestAnyOf1ConnectionStatusToJSONTyped(value?: WebhookPostRequestAnyOf1ConnectionStatus | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

