/* tslint:disable */
/* eslint-disable */
/**
 * Agent-Core API
 * Agent-Core Service - Control plane for multi-agent workflow orchestration
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhookPostRequestAnyOf3Phase
 */
export interface WebhookPostRequestAnyOf3Phase {
}

/**
 * Check if a given object implements the WebhookPostRequestAnyOf3Phase interface.
 */
export function instanceOfWebhookPostRequestAnyOf3Phase(value: object): value is WebhookPostRequestAnyOf3Phase {
    return true;
}

export function WebhookPostRequestAnyOf3PhaseFromJSON(json: any): WebhookPostRequestAnyOf3Phase {
    return WebhookPostRequestAnyOf3PhaseFromJSONTyped(json, false);
}

export function WebhookPostRequestAnyOf3PhaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookPostRequestAnyOf3Phase {
    return json;
}

export function WebhookPostRequestAnyOf3PhaseToJSON(json: any): WebhookPostRequestAnyOf3Phase {
    return WebhookPostRequestAnyOf3PhaseToJSONTyped(json, false);
}

export function WebhookPostRequestAnyOf3PhaseToJSONTyped(value?: WebhookPostRequestAnyOf3Phase | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

