/* tslint:disable */
/* eslint-disable */
/**
 * Agent-Core API
 * Agent-Core Service - Control plane for multi-agent workflow orchestration
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhookPostRequestAnyOf6
 */
export interface WebhookPostRequestAnyOf6 {
    /**
     * 
     * @type {string}
     * @memberof WebhookPostRequestAnyOf6
     */
    type: WebhookPostRequestAnyOf6TypeEnum;
    /**
     * 
     * @type {string}
     * @memberof WebhookPostRequestAnyOf6
     */
    orgId: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookPostRequestAnyOf6
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookPostRequestAnyOf6
     */
    timestamp: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookPostRequestAnyOf6
     */
    employeeId: string;
}


/**
 * @export
 */
export const WebhookPostRequestAnyOf6TypeEnum = {
    Employeecreated: 'employeecreated'
} as const;
export type WebhookPostRequestAnyOf6TypeEnum = typeof WebhookPostRequestAnyOf6TypeEnum[keyof typeof WebhookPostRequestAnyOf6TypeEnum];


/**
 * Check if a given object implements the WebhookPostRequestAnyOf6 interface.
 */
export function instanceOfWebhookPostRequestAnyOf6(value: object): value is WebhookPostRequestAnyOf6 {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('orgId' in value) || value['orgId'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('employeeId' in value) || value['employeeId'] === undefined) return false;
    return true;
}

export function WebhookPostRequestAnyOf6FromJSON(json: any): WebhookPostRequestAnyOf6 {
    return WebhookPostRequestAnyOf6FromJSONTyped(json, false);
}

export function WebhookPostRequestAnyOf6FromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookPostRequestAnyOf6 {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'orgId': json['orgId'],
        'userId': json['userId'],
        'timestamp': json['timestamp'],
        'employeeId': json['employeeId'],
    };
}

export function WebhookPostRequestAnyOf6ToJSON(json: any): WebhookPostRequestAnyOf6 {
    return WebhookPostRequestAnyOf6ToJSONTyped(json, false);
}

export function WebhookPostRequestAnyOf6ToJSONTyped(value?: WebhookPostRequestAnyOf6 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'orgId': value['orgId'],
        'userId': value['userId'],
        'timestamp': value['timestamp'],
        'employeeId': value['employeeId'],
    };
}

