/* tslint:disable */
/* eslint-disable */
/**
 * Agent-Core API
 * Agent-Core Service - Control plane for multi-agent workflow orchestration
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface WebhookPostRequestAnyOfAgentsInnerTrigger
 */
export interface WebhookPostRequestAnyOfAgentsInnerTrigger {
    /**
     * 
     * @type {string}
     * @memberof WebhookPostRequestAnyOfAgentsInnerTrigger
     */
    providerId: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookPostRequestAnyOfAgentsInnerTrigger
     */
    id: string;
    /**
     * Parameters for the trigger in the format specified by the get_triggers tool.
     * @type {any}
     * @memberof WebhookPostRequestAnyOfAgentsInnerTrigger
     */
    triggerParams: any | null;
}

/**
 * Check if a given object implements the WebhookPostRequestAnyOfAgentsInnerTrigger interface.
 */
export function instanceOfWebhookPostRequestAnyOfAgentsInnerTrigger(value: object): value is WebhookPostRequestAnyOfAgentsInnerTrigger {
    if (!('providerId' in value) || value['providerId'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('triggerParams' in value) || value['triggerParams'] === undefined) return false;
    return true;
}

export function WebhookPostRequestAnyOfAgentsInnerTriggerFromJSON(json: any): WebhookPostRequestAnyOfAgentsInnerTrigger {
    return WebhookPostRequestAnyOfAgentsInnerTriggerFromJSONTyped(json, false);
}

export function WebhookPostRequestAnyOfAgentsInnerTriggerFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookPostRequestAnyOfAgentsInnerTrigger {
    if (json == null) {
        return json;
    }
    return {
        
        'providerId': json['providerId'],
        'id': json['id'],
        'triggerParams': json['triggerParams'],
    };
}

export function WebhookPostRequestAnyOfAgentsInnerTriggerToJSON(json: any): WebhookPostRequestAnyOfAgentsInnerTrigger {
    return WebhookPostRequestAnyOfAgentsInnerTriggerToJSONTyped(json, false);
}

export function WebhookPostRequestAnyOfAgentsInnerTriggerToJSONTyped(value?: WebhookPostRequestAnyOfAgentsInnerTrigger | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'providerId': value['providerId'],
        'id': value['id'],
        'triggerParams': value['triggerParams'],
    };
}

