/* tslint:disable */
/* eslint-disable */
/**
 * Agent-Core API
 * Agent-Core Service - Control plane for multi-agent workflow orchestration
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { WebhookPostRequestAnyOf4RequestAnyOf1 } from './WebhookPostRequestAnyOf4RequestAnyOf1.js';
import {
    WebhookPostRequestAnyOf4RequestAnyOf1FromJSON,
    WebhookPostRequestAnyOf4RequestAnyOf1FromJSONTyped,
    WebhookPostRequestAnyOf4RequestAnyOf1ToJSON,
    WebhookPostRequestAnyOf4RequestAnyOf1ToJSONTyped,
} from './WebhookPostRequestAnyOf4RequestAnyOf1.js';
import type { WebhookPostRequestAnyOf4RequestAnyOf } from './WebhookPostRequestAnyOf4RequestAnyOf.js';
import {
    WebhookPostRequestAnyOf4RequestAnyOfFromJSON,
    WebhookPostRequestAnyOf4RequestAnyOfFromJSONTyped,
    WebhookPostRequestAnyOf4RequestAnyOfToJSON,
    WebhookPostRequestAnyOf4RequestAnyOfToJSONTyped,
} from './WebhookPostRequestAnyOf4RequestAnyOf.js';

/**
 * 
 * @export
 * @interface WebhookPostRequestAnyOf4Request
 */
export interface WebhookPostRequestAnyOf4Request {
    /**
     * 
     * @type {string}
     * @memberof WebhookPostRequestAnyOf4Request
     */
    type: WebhookPostRequestAnyOf4RequestTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof WebhookPostRequestAnyOf4Request
     */
    text: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof WebhookPostRequestAnyOf4Request
     */
    options: Array<string>;
}


/**
 * @export
 */
export const WebhookPostRequestAnyOf4RequestTypeEnum = {
    Text: 'text',
    Options: 'options'
} as const;
export type WebhookPostRequestAnyOf4RequestTypeEnum = typeof WebhookPostRequestAnyOf4RequestTypeEnum[keyof typeof WebhookPostRequestAnyOf4RequestTypeEnum];


/**
 * Check if a given object implements the WebhookPostRequestAnyOf4Request interface.
 */
export function instanceOfWebhookPostRequestAnyOf4Request(value: object): value is WebhookPostRequestAnyOf4Request {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('options' in value) || value['options'] === undefined) return false;
    return true;
}

export function WebhookPostRequestAnyOf4RequestFromJSON(json: any): WebhookPostRequestAnyOf4Request {
    return WebhookPostRequestAnyOf4RequestFromJSONTyped(json, false);
}

export function WebhookPostRequestAnyOf4RequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookPostRequestAnyOf4Request {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'text': json['text'],
        'options': json['options'],
    };
}

export function WebhookPostRequestAnyOf4RequestToJSON(json: any): WebhookPostRequestAnyOf4Request {
    return WebhookPostRequestAnyOf4RequestToJSONTyped(json, false);
}

export function WebhookPostRequestAnyOf4RequestToJSONTyped(value?: WebhookPostRequestAnyOf4Request | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'text': value['text'],
        'options': value['options'],
    };
}

