/* tslint:disable */
/* eslint-disable */
/**
 * Agent-Core API
 * Agent-Core Service - Control plane for multi-agent workflow orchestration
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhookPostRequestAnyOf5RequestAnyOf1
 */
export interface WebhookPostRequestAnyOf5RequestAnyOf1 {
    /**
     * 
     * @type {string}
     * @memberof WebhookPostRequestAnyOf5RequestAnyOf1
     */
    type: WebhookPostRequestAnyOf5RequestAnyOf1TypeEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof WebhookPostRequestAnyOf5RequestAnyOf1
     */
    options: Array<string>;
}


/**
 * @export
 */
export const WebhookPostRequestAnyOf5RequestAnyOf1TypeEnum = {
    Options: 'options'
} as const;
export type WebhookPostRequestAnyOf5RequestAnyOf1TypeEnum = typeof WebhookPostRequestAnyOf5RequestAnyOf1TypeEnum[keyof typeof WebhookPostRequestAnyOf5RequestAnyOf1TypeEnum];


/**
 * Check if a given object implements the WebhookPostRequestAnyOf5RequestAnyOf1 interface.
 */
export function instanceOfWebhookPostRequestAnyOf5RequestAnyOf1(value: object): value is WebhookPostRequestAnyOf5RequestAnyOf1 {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('options' in value) || value['options'] === undefined) return false;
    return true;
}

export function WebhookPostRequestAnyOf5RequestAnyOf1FromJSON(json: any): WebhookPostRequestAnyOf5RequestAnyOf1 {
    return WebhookPostRequestAnyOf5RequestAnyOf1FromJSONTyped(json, false);
}

export function WebhookPostRequestAnyOf5RequestAnyOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookPostRequestAnyOf5RequestAnyOf1 {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'options': json['options'],
    };
}

export function WebhookPostRequestAnyOf5RequestAnyOf1ToJSON(json: any): WebhookPostRequestAnyOf5RequestAnyOf1 {
    return WebhookPostRequestAnyOf5RequestAnyOf1ToJSONTyped(json, false);
}

export function WebhookPostRequestAnyOf5RequestAnyOf1ToJSONTyped(value?: WebhookPostRequestAnyOf5RequestAnyOf1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'options': value['options'],
    };
}

