/* tslint:disable */
/* eslint-disable */
/**
 * Agent-Core API
 * Agent-Core Service - Control plane for multi-agent workflow orchestration
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhookPostRequestAnyOf4ConnectionStatus
 */
export interface WebhookPostRequestAnyOf4ConnectionStatus {
}

/**
 * Check if a given object implements the WebhookPostRequestAnyOf4ConnectionStatus interface.
 */
export function instanceOfWebhookPostRequestAnyOf4ConnectionStatus(value: object): value is WebhookPostRequestAnyOf4ConnectionStatus {
    return true;
}

export function WebhookPostRequestAnyOf4ConnectionStatusFromJSON(json: any): WebhookPostRequestAnyOf4ConnectionStatus {
    return WebhookPostRequestAnyOf4ConnectionStatusFromJSONTyped(json, false);
}

export function WebhookPostRequestAnyOf4ConnectionStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookPostRequestAnyOf4ConnectionStatus {
    return json;
}

export function WebhookPostRequestAnyOf4ConnectionStatusToJSON(json: any): WebhookPostRequestAnyOf4ConnectionStatus {
    return WebhookPostRequestAnyOf4ConnectionStatusToJSONTyped(json, false);
}

export function WebhookPostRequestAnyOf4ConnectionStatusToJSONTyped(value?: WebhookPostRequestAnyOf4ConnectionStatus | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

