/* tslint:disable */
/* eslint-disable */
/**
 * Agent-Core API
 * Agent-Core Service - Control plane for multi-agent workflow orchestration
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.js";
import type { WebhookPostRequestAnyOf9Status } from "./WebhookPostRequestAnyOf9Status.js";
import {
  WebhookPostRequestAnyOf9StatusFromJSON,
  WebhookPostRequestAnyOf9StatusFromJSONTyped,
  WebhookPostRequestAnyOf9StatusToJSON,
  WebhookPostRequestAnyOf9StatusToJSONTyped,
} from "./WebhookPostRequestAnyOf9Status.js";
import type { V1AgentsIdPutRequestCapabilitiesInner } from "./V1AgentsIdPutRequestCapabilitiesInner.js";
import {
  V1AgentsIdPutRequestCapabilitiesInnerFromJSON,
  V1AgentsIdPutRequestCapabilitiesInnerFromJSONTyped,
  V1AgentsIdPutRequestCapabilitiesInnerToJSON,
  V1AgentsIdPutRequestCapabilitiesInnerToJSONTyped,
} from "./V1AgentsIdPutRequestCapabilitiesInner.js";

/**
 *
 * @export
 * @interface WebhookPostRequestAnyOf11
 */
export interface WebhookPostRequestAnyOf11 {
  /**
   *
   * @type {string}
   * @memberof WebhookPostRequestAnyOf11
   */
  type: WebhookPostRequestAnyOf11TypeEnum;
  /**
   *
   * @type {string}
   * @memberof WebhookPostRequestAnyOf11
   */
  orgId: string;
  /**
   *
   * @type {string}
   * @memberof WebhookPostRequestAnyOf11
   */
  userId: string;
  /**
   *
   * @type {string}
   * @memberof WebhookPostRequestAnyOf11
   */
  timestamp: string;
  /**
   *
   * @type {string}
   * @memberof WebhookPostRequestAnyOf11
   */
  agentId: string;
  /**
   *
   * @type {V1AgentsIdPutRequestCapabilitiesInner}
   * @memberof WebhookPostRequestAnyOf11
   */
  capability: V1AgentsIdPutRequestCapabilitiesInner;
  /**
   *
   * @type {string}
   * @memberof WebhookPostRequestAnyOf11
   */
  executionId: string;
  /**
   *
   * @type {{ [key: string]: any; }}
   * @memberof WebhookPostRequestAnyOf11
   */
  result: { [key: string]: any };
  /**
   *
   * @type {WebhookPostRequestAnyOf9Status}
   * @memberof WebhookPostRequestAnyOf11
   */
  status: WebhookPostRequestAnyOf9Status;
}

/**
 * @export
 */
export const WebhookPostRequestAnyOf11TypeEnum = {
  Actioncompleted: "actioncompleted",
} as const;
export type WebhookPostRequestAnyOf11TypeEnum =
  (typeof WebhookPostRequestAnyOf11TypeEnum)[keyof typeof WebhookPostRequestAnyOf11TypeEnum];

/**
 * Check if a given object implements the WebhookPostRequestAnyOf11 interface.
 */
export function instanceOfWebhookPostRequestAnyOf11(
  value: object,
): value is WebhookPostRequestAnyOf11 {
  if (!("type" in value) || value["type"] === undefined) return false;
  if (!("orgId" in value) || value["orgId"] === undefined) return false;
  if (!("userId" in value) || value["userId"] === undefined) return false;
  if (!("timestamp" in value) || value["timestamp"] === undefined) return false;
  if (!("agentId" in value) || value["agentId"] === undefined) return false;
  if (!("capability" in value) || value["capability"] === undefined)
    return false;
  if (!("executionId" in value) || value["executionId"] === undefined)
    return false;
  if (!("result" in value) || value["result"] === undefined) return false;
  if (!("status" in value) || value["status"] === undefined) return false;
  return true;
}

export function WebhookPostRequestAnyOf11FromJSON(
  json: any,
): WebhookPostRequestAnyOf11 {
  return WebhookPostRequestAnyOf11FromJSONTyped(json, false);
}

export function WebhookPostRequestAnyOf11FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): WebhookPostRequestAnyOf11 {
  if (json == null) {
    return json;
  }
  return {
    type: json["type"],
    orgId: json["orgId"],
    userId: json["userId"],
    timestamp: json["timestamp"],
    agentId: json["agentId"],
    capability: V1AgentsIdPutRequestCapabilitiesInnerFromJSON(
      json["capability"],
    ),
    executionId: json["executionId"],
    result: json["result"],
    status: WebhookPostRequestAnyOf9StatusFromJSON(json["status"]),
  };
}

export function WebhookPostRequestAnyOf11ToJSON(
  json: any,
): WebhookPostRequestAnyOf11 {
  return WebhookPostRequestAnyOf11ToJSONTyped(json, false);
}

export function WebhookPostRequestAnyOf11ToJSONTyped(
  value?: WebhookPostRequestAnyOf11 | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    type: value["type"],
    orgId: value["orgId"],
    userId: value["userId"],
    timestamp: value["timestamp"],
    agentId: value["agentId"],
    capability: V1AgentsIdPutRequestCapabilitiesInnerToJSON(
      value["capability"],
    ),
    executionId: value["executionId"],
    result: value["result"],
    status: WebhookPostRequestAnyOf9StatusToJSON(value["status"]),
  };
}
