/* tslint:disable */
/* eslint-disable */
/**
 * Agent-Core API
 * Agent-Core Service - Control plane for multi-agent workflow orchestration
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface WebhookPostRequestAnyOfPhase
 */
export interface WebhookPostRequestAnyOfPhase {
}

/**
 * Check if a given object implements the WebhookPostRequestAnyOfPhase interface.
 */
export function instanceOfWebhookPostRequestAnyOfPhase(value: object): value is WebhookPostRequestAnyOfPhase {
    return true;
}

export function WebhookPostRequestAnyOfPhaseFromJSON(json: any): WebhookPostRequestAnyOfPhase {
    return WebhookPostRequestAnyOfPhaseFromJSONTyped(json, false);
}

export function WebhookPostRequestAnyOfPhaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookPostRequestAnyOfPhase {
    return json;
}

export function WebhookPostRequestAnyOfPhaseToJSON(json: any): WebhookPostRequestAnyOfPhase {
    return WebhookPostRequestAnyOfPhaseToJSONTyped(json, false);
}

export function WebhookPostRequestAnyOfPhaseToJSONTyped(value?: WebhookPostRequestAnyOfPhase | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

