/* tslint:disable */
/* eslint-disable */
/**
 * Agent-Core API
 * Agent-Core Service - Control plane for multi-agent workflow orchestration
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.js";
/**
 *
 * @export
 * @interface WebhookPostRequestAnyOfUnsatisfiedWorkflowsInner
 */
export interface WebhookPostRequestAnyOfUnsatisfiedWorkflowsInner {
  /**
   *
   * @type {string}
   * @memberof WebhookPostRequestAnyOfUnsatisfiedWorkflowsInner
   */
  description: string;
  /**
   *
   * @type {string}
   * @memberof WebhookPostRequestAnyOfUnsatisfiedWorkflowsInner
   */
  explanation: string;
}

/**
 * Check if a given object implements the WebhookPostRequestAnyOfUnsatisfiedWorkflowsInner interface.
 */
export function instanceOfWebhookPostRequestAnyOfUnsatisfiedWorkflowsInner(
  value: object,
): value is WebhookPostRequestAnyOfUnsatisfiedWorkflowsInner {
  if (!("description" in value) || value["description"] === undefined)
    return false;
  if (!("explanation" in value) || value["explanation"] === undefined)
    return false;
  return true;
}

export function WebhookPostRequestAnyOfUnsatisfiedWorkflowsInnerFromJSON(
  json: any,
): WebhookPostRequestAnyOfUnsatisfiedWorkflowsInner {
  return WebhookPostRequestAnyOfUnsatisfiedWorkflowsInnerFromJSONTyped(
    json,
    false,
  );
}

export function WebhookPostRequestAnyOfUnsatisfiedWorkflowsInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): WebhookPostRequestAnyOfUnsatisfiedWorkflowsInner {
  if (json == null) {
    return json;
  }
  return {
    description: json["description"],
    explanation: json["explanation"],
  };
}

export function WebhookPostRequestAnyOfUnsatisfiedWorkflowsInnerToJSON(
  json: any,
): WebhookPostRequestAnyOfUnsatisfiedWorkflowsInner {
  return WebhookPostRequestAnyOfUnsatisfiedWorkflowsInnerToJSONTyped(
    json,
    false,
  );
}

export function WebhookPostRequestAnyOfUnsatisfiedWorkflowsInnerToJSONTyped(
  value?: WebhookPostRequestAnyOfUnsatisfiedWorkflowsInner | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    description: value["description"],
    explanation: value["explanation"],
  };
}
