/* tslint:disable */
/* eslint-disable */
/**
 * Agent-Core API
 * Agent-Core Service - Control plane for multi-agent workflow orchestration
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.js";
/**
 *
 * @export
 * @interface WebhookPostRequestAnyOf4RequestAnyOf
 */
export interface WebhookPostRequestAnyOf4RequestAnyOf {
  /**
   *
   * @type {string}
   * @memberof WebhookPostRequestAnyOf4RequestAnyOf
   */
  type: WebhookPostRequestAnyOf4RequestAnyOfTypeEnum;
  /**
   *
   * @type {string}
   * @memberof WebhookPostRequestAnyOf4RequestAnyOf
   */
  text: string;
}

/**
 * @export
 */
export const WebhookPostRequestAnyOf4RequestAnyOfTypeEnum = {
  Text: "text",
} as const;
export type WebhookPostRequestAnyOf4RequestAnyOfTypeEnum =
  (typeof WebhookPostRequestAnyOf4RequestAnyOfTypeEnum)[keyof typeof WebhookPostRequestAnyOf4RequestAnyOfTypeEnum];

/**
 * Check if a given object implements the WebhookPostRequestAnyOf4RequestAnyOf interface.
 */
export function instanceOfWebhookPostRequestAnyOf4RequestAnyOf(
  value: object,
): value is WebhookPostRequestAnyOf4RequestAnyOf {
  if (!("type" in value) || value["type"] === undefined) return false;
  if (!("text" in value) || value["text"] === undefined) return false;
  return true;
}

export function WebhookPostRequestAnyOf4RequestAnyOfFromJSON(
  json: any,
): WebhookPostRequestAnyOf4RequestAnyOf {
  return WebhookPostRequestAnyOf4RequestAnyOfFromJSONTyped(json, false);
}

export function WebhookPostRequestAnyOf4RequestAnyOfFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): WebhookPostRequestAnyOf4RequestAnyOf {
  if (json == null) {
    return json;
  }
  return {
    type: json["type"],
    text: json["text"],
  };
}

export function WebhookPostRequestAnyOf4RequestAnyOfToJSON(
  json: any,
): WebhookPostRequestAnyOf4RequestAnyOf {
  return WebhookPostRequestAnyOf4RequestAnyOfToJSONTyped(json, false);
}

export function WebhookPostRequestAnyOf4RequestAnyOfToJSONTyped(
  value?: WebhookPostRequestAnyOf4RequestAnyOf | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    type: value["type"],
    text: value["text"],
  };
}
