/* tslint:disable */
/* eslint-disable */
/**
 * Agent-Core API
 * Agent-Core Service - Control plane for multi-agent workflow orchestration
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhookPostRequestAnyOf2
 */
export interface WebhookPostRequestAnyOf2 {
    /**
     * 
     * @type {string}
     * @memberof WebhookPostRequestAnyOf2
     */
    type: WebhookPostRequestAnyOf2TypeEnum;
    /**
     * 
     * @type {string}
     * @memberof WebhookPostRequestAnyOf2
     */
    orgId: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookPostRequestAnyOf2
     */
    timestamp: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookPostRequestAnyOf2
     */
    agentId: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookPostRequestAnyOf2
     */
    executionId: string;
    /**
     * 
     * @type {any}
     * @memberof WebhookPostRequestAnyOf2
     */
    resume: any | null;
    /**
     * 
     * @type {string}
     * @memberof WebhookPostRequestAnyOf2
     */
    userId: string;
}


/**
 * @export
 */
export const WebhookPostRequestAnyOf2TypeEnum = {
    Resumeintent: 'resumeintent'
} as const;
export type WebhookPostRequestAnyOf2TypeEnum = typeof WebhookPostRequestAnyOf2TypeEnum[keyof typeof WebhookPostRequestAnyOf2TypeEnum];


/**
 * Check if a given object implements the WebhookPostRequestAnyOf2 interface.
 */
export function instanceOfWebhookPostRequestAnyOf2(value: object): value is WebhookPostRequestAnyOf2 {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('orgId' in value) || value['orgId'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('agentId' in value) || value['agentId'] === undefined) return false;
    if (!('executionId' in value) || value['executionId'] === undefined) return false;
    if (!('resume' in value) || value['resume'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function WebhookPostRequestAnyOf2FromJSON(json: any): WebhookPostRequestAnyOf2 {
    return WebhookPostRequestAnyOf2FromJSONTyped(json, false);
}

export function WebhookPostRequestAnyOf2FromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookPostRequestAnyOf2 {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'orgId': json['orgId'],
        'timestamp': json['timestamp'],
        'agentId': json['agentId'],
        'executionId': json['executionId'],
        'resume': json['resume'],
        'userId': json['userId'],
    };
}

export function WebhookPostRequestAnyOf2ToJSON(json: any): WebhookPostRequestAnyOf2 {
    return WebhookPostRequestAnyOf2ToJSONTyped(json, false);
}

export function WebhookPostRequestAnyOf2ToJSONTyped(value?: WebhookPostRequestAnyOf2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'orgId': value['orgId'],
        'timestamp': value['timestamp'],
        'agentId': value['agentId'],
        'executionId': value['executionId'],
        'resume': value['resume'],
        'userId': value['userId'],
    };
}

