/* tslint:disable */
/* eslint-disable */
/**
 * Agent-Core API
 * Agent-Core Service - Control plane for multi-agent workflow orchestration
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebhookPostRequestAnyOf7RequestAnyOf1 } from './WebhookPostRequestAnyOf7RequestAnyOf1';
import {
    WebhookPostRequestAnyOf7RequestAnyOf1FromJSON,
    WebhookPostRequestAnyOf7RequestAnyOf1FromJSONTyped,
    WebhookPostRequestAnyOf7RequestAnyOf1ToJSON,
    WebhookPostRequestAnyOf7RequestAnyOf1ToJSONTyped,
} from './WebhookPostRequestAnyOf7RequestAnyOf1';
import type { WebhookPostRequestAnyOf7RequestAnyOf } from './WebhookPostRequestAnyOf7RequestAnyOf';
import {
    WebhookPostRequestAnyOf7RequestAnyOfFromJSON,
    WebhookPostRequestAnyOf7RequestAnyOfFromJSONTyped,
    WebhookPostRequestAnyOf7RequestAnyOfToJSON,
    WebhookPostRequestAnyOf7RequestAnyOfToJSONTyped,
} from './WebhookPostRequestAnyOf7RequestAnyOf';

/**
 * 
 * @export
 * @interface WebhookPostRequestAnyOf7Request
 */
export interface WebhookPostRequestAnyOf7Request {
    /**
     * 
     * @type {string}
     * @memberof WebhookPostRequestAnyOf7Request
     */
    type: WebhookPostRequestAnyOf7RequestTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof WebhookPostRequestAnyOf7Request
     */
    text: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof WebhookPostRequestAnyOf7Request
     */
    options: Array<string>;
}


/**
 * @export
 */
export const WebhookPostRequestAnyOf7RequestTypeEnum = {
    Text: 'text',
    Options: 'options'
} as const;
export type WebhookPostRequestAnyOf7RequestTypeEnum = typeof WebhookPostRequestAnyOf7RequestTypeEnum[keyof typeof WebhookPostRequestAnyOf7RequestTypeEnum];


/**
 * Check if a given object implements the WebhookPostRequestAnyOf7Request interface.
 */
export function instanceOfWebhookPostRequestAnyOf7Request(value: object): value is WebhookPostRequestAnyOf7Request {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('options' in value) || value['options'] === undefined) return false;
    return true;
}

export function WebhookPostRequestAnyOf7RequestFromJSON(json: any): WebhookPostRequestAnyOf7Request {
    return WebhookPostRequestAnyOf7RequestFromJSONTyped(json, false);
}

export function WebhookPostRequestAnyOf7RequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookPostRequestAnyOf7Request {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'text': json['text'],
        'options': json['options'],
    };
}

export function WebhookPostRequestAnyOf7RequestToJSON(json: any): WebhookPostRequestAnyOf7Request {
    return WebhookPostRequestAnyOf7RequestToJSONTyped(json, false);
}

export function WebhookPostRequestAnyOf7RequestToJSONTyped(value?: WebhookPostRequestAnyOf7Request | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'text': value['text'],
        'options': value['options'],
    };
}

