/* tslint:disable */
/* eslint-disable */
/**
 * Agent-Core API
 * Agent-Core Service - Control plane for multi-agent workflow orchestration
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.js";
/**
 *
 * @export
 * @interface WebhookPostRequestAnyOf3
 */
export interface WebhookPostRequestAnyOf3 {
  /**
   *
   * @type {string}
   * @memberof WebhookPostRequestAnyOf3
   */
  type: WebhookPostRequestAnyOf3TypeEnum;
  /**
   *
   * @type {string}
   * @memberof WebhookPostRequestAnyOf3
   */
  orgId: string;
  /**
   *
   * @type {string}
   * @memberof WebhookPostRequestAnyOf3
   */
  userId: string;
  /**
   *
   * @type {string}
   * @memberof WebhookPostRequestAnyOf3
   */
  timestamp: string;
  /**
   *
   * @type {string}
   * @memberof WebhookPostRequestAnyOf3
   */
  employeeId: string;
}

/**
 * @export
 */
export const WebhookPostRequestAnyOf3TypeEnum = {
  Employeecreated: "employeecreated",
} as const;
export type WebhookPostRequestAnyOf3TypeEnum =
  (typeof WebhookPostRequestAnyOf3TypeEnum)[keyof typeof WebhookPostRequestAnyOf3TypeEnum];

/**
 * Check if a given object implements the WebhookPostRequestAnyOf3 interface.
 */
export function instanceOfWebhookPostRequestAnyOf3(
  value: object,
): value is WebhookPostRequestAnyOf3 {
  if (!("type" in value) || value["type"] === undefined) return false;
  if (!("orgId" in value) || value["orgId"] === undefined) return false;
  if (!("userId" in value) || value["userId"] === undefined) return false;
  if (!("timestamp" in value) || value["timestamp"] === undefined) return false;
  if (!("employeeId" in value) || value["employeeId"] === undefined)
    return false;
  return true;
}

export function WebhookPostRequestAnyOf3FromJSON(
  json: any,
): WebhookPostRequestAnyOf3 {
  return WebhookPostRequestAnyOf3FromJSONTyped(json, false);
}

export function WebhookPostRequestAnyOf3FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): WebhookPostRequestAnyOf3 {
  if (json == null) {
    return json;
  }
  return {
    type: json["type"],
    orgId: json["orgId"],
    userId: json["userId"],
    timestamp: json["timestamp"],
    employeeId: json["employeeId"],
  };
}

export function WebhookPostRequestAnyOf3ToJSON(
  json: any,
): WebhookPostRequestAnyOf3 {
  return WebhookPostRequestAnyOf3ToJSONTyped(json, false);
}

export function WebhookPostRequestAnyOf3ToJSONTyped(
  value?: WebhookPostRequestAnyOf3 | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    type: value["type"],
    orgId: value["orgId"],
    userId: value["userId"],
    timestamp: value["timestamp"],
    employeeId: value["employeeId"],
  };
}
