/* tslint:disable */
/* eslint-disable */
/**
 * Agent-Core API
 * Agent-Core Service - Control plane for multi-agent workflow orchestration
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.js";
import type { V1AgentsIdPutRequestCapabilitiesInner } from "./V1AgentsIdPutRequestCapabilitiesInner.js";
import {
  V1AgentsIdPutRequestCapabilitiesInnerFromJSON,
  V1AgentsIdPutRequestCapabilitiesInnerFromJSONTyped,
  V1AgentsIdPutRequestCapabilitiesInnerToJSON,
  V1AgentsIdPutRequestCapabilitiesInnerToJSONTyped,
} from "./V1AgentsIdPutRequestCapabilitiesInner.js";

/**
 *
 * @export
 * @interface WebhookPostRequestAnyOf10
 */
export interface WebhookPostRequestAnyOf10 {
  /**
   *
   * @type {string}
   * @memberof WebhookPostRequestAnyOf10
   */
  type: WebhookPostRequestAnyOf10TypeEnum;
  /**
   *
   * @type {string}
   * @memberof WebhookPostRequestAnyOf10
   */
  orgId: string;
  /**
   *
   * @type {string}
   * @memberof WebhookPostRequestAnyOf10
   */
  userId: string;
  /**
   *
   * @type {string}
   * @memberof WebhookPostRequestAnyOf10
   */
  timestamp: string;
  /**
   *
   * @type {string}
   * @memberof WebhookPostRequestAnyOf10
   */
  agentId: string;
  /**
   *
   * @type {V1AgentsIdPutRequestCapabilitiesInner}
   * @memberof WebhookPostRequestAnyOf10
   */
  capability: V1AgentsIdPutRequestCapabilitiesInner;
  /**
   *
   * @type {string}
   * @memberof WebhookPostRequestAnyOf10
   */
  executionId: string;
}

/**
 * @export
 */
export const WebhookPostRequestAnyOf10TypeEnum = {
  Actioninitiated: "actioninitiated",
} as const;
export type WebhookPostRequestAnyOf10TypeEnum =
  (typeof WebhookPostRequestAnyOf10TypeEnum)[keyof typeof WebhookPostRequestAnyOf10TypeEnum];

/**
 * Check if a given object implements the WebhookPostRequestAnyOf10 interface.
 */
export function instanceOfWebhookPostRequestAnyOf10(
  value: object,
): value is WebhookPostRequestAnyOf10 {
  if (!("type" in value) || value["type"] === undefined) return false;
  if (!("orgId" in value) || value["orgId"] === undefined) return false;
  if (!("userId" in value) || value["userId"] === undefined) return false;
  if (!("timestamp" in value) || value["timestamp"] === undefined) return false;
  if (!("agentId" in value) || value["agentId"] === undefined) return false;
  if (!("capability" in value) || value["capability"] === undefined)
    return false;
  if (!("executionId" in value) || value["executionId"] === undefined)
    return false;
  return true;
}

export function WebhookPostRequestAnyOf10FromJSON(
  json: any,
): WebhookPostRequestAnyOf10 {
  return WebhookPostRequestAnyOf10FromJSONTyped(json, false);
}

export function WebhookPostRequestAnyOf10FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): WebhookPostRequestAnyOf10 {
  if (json == null) {
    return json;
  }
  return {
    type: json["type"],
    orgId: json["orgId"],
    userId: json["userId"],
    timestamp: json["timestamp"],
    agentId: json["agentId"],
    capability: V1AgentsIdPutRequestCapabilitiesInnerFromJSON(
      json["capability"],
    ),
    executionId: json["executionId"],
  };
}

export function WebhookPostRequestAnyOf10ToJSON(
  json: any,
): WebhookPostRequestAnyOf10 {
  return WebhookPostRequestAnyOf10ToJSONTyped(json, false);
}

export function WebhookPostRequestAnyOf10ToJSONTyped(
  value?: WebhookPostRequestAnyOf10 | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    type: value["type"],
    orgId: value["orgId"],
    userId: value["userId"],
    timestamp: value["timestamp"],
    agentId: value["agentId"],
    capability: V1AgentsIdPutRequestCapabilitiesInnerToJSON(
      value["capability"],
    ),
    executionId: value["executionId"],
  };
}
