/* tslint:disable */
/* eslint-disable */
/**
 * Agent-Core API
 * Agent-Core Service - Control plane for multi-agent workflow orchestration
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebhookPostRequestAnyOf3AgentsInnerTrigger } from './WebhookPostRequestAnyOf3AgentsInnerTrigger';
import {
    WebhookPostRequestAnyOf3AgentsInnerTriggerFromJSON,
    WebhookPostRequestAnyOf3AgentsInnerTriggerFromJSONTyped,
    WebhookPostRequestAnyOf3AgentsInnerTriggerToJSON,
    WebhookPostRequestAnyOf3AgentsInnerTriggerToJSONTyped,
} from './WebhookPostRequestAnyOf3AgentsInnerTrigger';
import type { V1AgentsIdPutRequestCapabilitiesInner } from './V1AgentsIdPutRequestCapabilitiesInner';
import {
    V1AgentsIdPutRequestCapabilitiesInnerFromJSON,
    V1AgentsIdPutRequestCapabilitiesInnerFromJSONTyped,
    V1AgentsIdPutRequestCapabilitiesInnerToJSON,
    V1AgentsIdPutRequestCapabilitiesInnerToJSONTyped,
} from './V1AgentsIdPutRequestCapabilitiesInner';

/**
 * 
 * @export
 * @interface WebhookPostRequestAnyOf3AgentsInner
 */
export interface WebhookPostRequestAnyOf3AgentsInner {
    /**
     * 
     * @type {string}
     * @memberof WebhookPostRequestAnyOf3AgentsInner
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookPostRequestAnyOf3AgentsInner
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookPostRequestAnyOf3AgentsInner
     */
    description: string;
    /**
     * 
     * @type {Array<V1AgentsIdPutRequestCapabilitiesInner>}
     * @memberof WebhookPostRequestAnyOf3AgentsInner
     */
    capabilities: Array<V1AgentsIdPutRequestCapabilitiesInner>;
    /**
     * 
     * @type {WebhookPostRequestAnyOf3AgentsInnerTrigger}
     * @memberof WebhookPostRequestAnyOf3AgentsInner
     */
    trigger: WebhookPostRequestAnyOf3AgentsInnerTrigger;
    /**
     * 
     * @type {string}
     * @memberof WebhookPostRequestAnyOf3AgentsInner
     */
    prompt: string;
}

/**
 * Check if a given object implements the WebhookPostRequestAnyOf3AgentsInner interface.
 */
export function instanceOfWebhookPostRequestAnyOf3AgentsInner(value: object): value is WebhookPostRequestAnyOf3AgentsInner {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('capabilities' in value) || value['capabilities'] === undefined) return false;
    if (!('trigger' in value) || value['trigger'] === undefined) return false;
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    return true;
}

export function WebhookPostRequestAnyOf3AgentsInnerFromJSON(json: any): WebhookPostRequestAnyOf3AgentsInner {
    return WebhookPostRequestAnyOf3AgentsInnerFromJSONTyped(json, false);
}

export function WebhookPostRequestAnyOf3AgentsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookPostRequestAnyOf3AgentsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'description': json['description'],
        'capabilities': ((json['capabilities'] as Array<any>).map(V1AgentsIdPutRequestCapabilitiesInnerFromJSON)),
        'trigger': WebhookPostRequestAnyOf3AgentsInnerTriggerFromJSON(json['trigger']),
        'prompt': json['prompt'],
    };
}

export function WebhookPostRequestAnyOf3AgentsInnerToJSON(json: any): WebhookPostRequestAnyOf3AgentsInner {
    return WebhookPostRequestAnyOf3AgentsInnerToJSONTyped(json, false);
}

export function WebhookPostRequestAnyOf3AgentsInnerToJSONTyped(value?: WebhookPostRequestAnyOf3AgentsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'capabilities': ((value['capabilities'] as Array<any>).map(V1AgentsIdPutRequestCapabilitiesInnerToJSON)),
        'trigger': WebhookPostRequestAnyOf3AgentsInnerTriggerToJSON(value['trigger']),
        'prompt': value['prompt'],
    };
}

