/* tslint:disable */
/* eslint-disable */
/**
 * Agent-Core API
 * Agent-Core Service - Control plane for multi-agent workflow orchestration
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhookPostRequestAnyOf5RequestAnyOf
 */
export interface WebhookPostRequestAnyOf5RequestAnyOf {
    /**
     * 
     * @type {string}
     * @memberof WebhookPostRequestAnyOf5RequestAnyOf
     */
    type: WebhookPostRequestAnyOf5RequestAnyOfTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof WebhookPostRequestAnyOf5RequestAnyOf
     */
    text: string;
}


/**
 * @export
 */
export const WebhookPostRequestAnyOf5RequestAnyOfTypeEnum = {
    Text: 'text'
} as const;
export type WebhookPostRequestAnyOf5RequestAnyOfTypeEnum = typeof WebhookPostRequestAnyOf5RequestAnyOfTypeEnum[keyof typeof WebhookPostRequestAnyOf5RequestAnyOfTypeEnum];


/**
 * Check if a given object implements the WebhookPostRequestAnyOf5RequestAnyOf interface.
 */
export function instanceOfWebhookPostRequestAnyOf5RequestAnyOf(value: object): value is WebhookPostRequestAnyOf5RequestAnyOf {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function WebhookPostRequestAnyOf5RequestAnyOfFromJSON(json: any): WebhookPostRequestAnyOf5RequestAnyOf {
    return WebhookPostRequestAnyOf5RequestAnyOfFromJSONTyped(json, false);
}

export function WebhookPostRequestAnyOf5RequestAnyOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookPostRequestAnyOf5RequestAnyOf {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'text': json['text'],
    };
}

export function WebhookPostRequestAnyOf5RequestAnyOfToJSON(json: any): WebhookPostRequestAnyOf5RequestAnyOf {
    return WebhookPostRequestAnyOf5RequestAnyOfToJSONTyped(json, false);
}

export function WebhookPostRequestAnyOf5RequestAnyOfToJSONTyped(value?: WebhookPostRequestAnyOf5RequestAnyOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'text': value['text'],
    };
}

