/* tslint:disable */
/* eslint-disable */
/**
 * Agent-Core API
 * Agent-Core Service - Control plane for multi-agent workflow orchestration
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebhookPostRequestAnyOf3AgentsInner } from './WebhookPostRequestAnyOf3AgentsInner';
import {
    WebhookPostRequestAnyOf3AgentsInnerFromJSON,
    WebhookPostRequestAnyOf3AgentsInnerFromJSONTyped,
    WebhookPostRequestAnyOf3AgentsInnerToJSON,
    WebhookPostRequestAnyOf3AgentsInnerToJSONTyped,
} from './WebhookPostRequestAnyOf3AgentsInner';

/**
 * 
 * @export
 * @interface WebhookPostRequestAnyOf5
 */
export interface WebhookPostRequestAnyOf5 {
    /**
     * 
     * @type {string}
     * @memberof WebhookPostRequestAnyOf5
     */
    type: WebhookPostRequestAnyOf5TypeEnum;
    /**
     * 
     * @type {string}
     * @memberof WebhookPostRequestAnyOf5
     */
    orgId: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookPostRequestAnyOf5
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookPostRequestAnyOf5
     */
    timestamp: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookPostRequestAnyOf5
     */
    agentId: string;
    /**
     * 
     * @type {WebhookPostRequestAnyOf3AgentsInner}
     * @memberof WebhookPostRequestAnyOf5
     */
    agent: WebhookPostRequestAnyOf3AgentsInner;
}


/**
 * @export
 */
export const WebhookPostRequestAnyOf5TypeEnum = {
    Agentcreated: 'agentcreated'
} as const;
export type WebhookPostRequestAnyOf5TypeEnum = typeof WebhookPostRequestAnyOf5TypeEnum[keyof typeof WebhookPostRequestAnyOf5TypeEnum];


/**
 * Check if a given object implements the WebhookPostRequestAnyOf5 interface.
 */
export function instanceOfWebhookPostRequestAnyOf5(value: object): value is WebhookPostRequestAnyOf5 {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('orgId' in value) || value['orgId'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('agentId' in value) || value['agentId'] === undefined) return false;
    if (!('agent' in value) || value['agent'] === undefined) return false;
    return true;
}

export function WebhookPostRequestAnyOf5FromJSON(json: any): WebhookPostRequestAnyOf5 {
    return WebhookPostRequestAnyOf5FromJSONTyped(json, false);
}

export function WebhookPostRequestAnyOf5FromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookPostRequestAnyOf5 {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'orgId': json['orgId'],
        'userId': json['userId'],
        'timestamp': json['timestamp'],
        'agentId': json['agentId'],
        'agent': WebhookPostRequestAnyOf3AgentsInnerFromJSON(json['agent']),
    };
}

export function WebhookPostRequestAnyOf5ToJSON(json: any): WebhookPostRequestAnyOf5 {
    return WebhookPostRequestAnyOf5ToJSONTyped(json, false);
}

export function WebhookPostRequestAnyOf5ToJSONTyped(value?: WebhookPostRequestAnyOf5 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'orgId': value['orgId'],
        'userId': value['userId'],
        'timestamp': value['timestamp'],
        'agentId': value['agentId'],
        'agent': WebhookPostRequestAnyOf3AgentsInnerToJSON(value['agent']),
    };
}

