/* tslint:disable */
/* eslint-disable */
/**
 * Agent-Core API
 * Agent-Core Service - Control plane for multi-agent workflow orchestration
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface WebhookPost200Response
 */
export interface WebhookPost200Response {
    /**
     * 
     * @type {string}
     * @memberof WebhookPost200Response
     */
    message: WebhookPost200ResponseMessageEnum;
}


/**
 * @export
 */
export const WebhookPost200ResponseMessageEnum = {
    Ok: 'ok'
} as const;
export type WebhookPost200ResponseMessageEnum = typeof WebhookPost200ResponseMessageEnum[keyof typeof WebhookPost200ResponseMessageEnum];


/**
 * Check if a given object implements the WebhookPost200Response interface.
 */
export function instanceOfWebhookPost200Response(value: object): value is WebhookPost200Response {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function WebhookPost200ResponseFromJSON(json: any): WebhookPost200Response {
    return WebhookPost200ResponseFromJSONTyped(json, false);
}

export function WebhookPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function WebhookPost200ResponseToJSON(json: any): WebhookPost200Response {
    return WebhookPost200ResponseToJSONTyped(json, false);
}

export function WebhookPost200ResponseToJSONTyped(value?: WebhookPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

