/* tslint:disable */
/* eslint-disable */
/**
 * Agent-Core API
 * Agent-Core Service - Control plane for multi-agent workflow orchestration
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhookPostRequestAnyOf3UnsatisfiedWorkflowsInner
 */
export interface WebhookPostRequestAnyOf3UnsatisfiedWorkflowsInner {
    /**
     * 
     * @type {string}
     * @memberof WebhookPostRequestAnyOf3UnsatisfiedWorkflowsInner
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookPostRequestAnyOf3UnsatisfiedWorkflowsInner
     */
    explanation: string;
}

/**
 * Check if a given object implements the WebhookPostRequestAnyOf3UnsatisfiedWorkflowsInner interface.
 */
export function instanceOfWebhookPostRequestAnyOf3UnsatisfiedWorkflowsInner(value: object): value is WebhookPostRequestAnyOf3UnsatisfiedWorkflowsInner {
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('explanation' in value) || value['explanation'] === undefined) return false;
    return true;
}

export function WebhookPostRequestAnyOf3UnsatisfiedWorkflowsInnerFromJSON(json: any): WebhookPostRequestAnyOf3UnsatisfiedWorkflowsInner {
    return WebhookPostRequestAnyOf3UnsatisfiedWorkflowsInnerFromJSONTyped(json, false);
}

export function WebhookPostRequestAnyOf3UnsatisfiedWorkflowsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookPostRequestAnyOf3UnsatisfiedWorkflowsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'],
        'explanation': json['explanation'],
    };
}

export function WebhookPostRequestAnyOf3UnsatisfiedWorkflowsInnerToJSON(json: any): WebhookPostRequestAnyOf3UnsatisfiedWorkflowsInner {
    return WebhookPostRequestAnyOf3UnsatisfiedWorkflowsInnerToJSONTyped(json, false);
}

export function WebhookPostRequestAnyOf3UnsatisfiedWorkflowsInnerToJSONTyped(value?: WebhookPostRequestAnyOf3UnsatisfiedWorkflowsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'explanation': value['explanation'],
    };
}

