/* tslint:disable */
/* eslint-disable */
/**
 * Agent-Core API
 * Agent-Core Service - Control plane for multi-agent workflow orchestration
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.js";
import type { WebhookPostRequestAnyOf4Request } from "./WebhookPostRequestAnyOf4Request.js";
import {
  WebhookPostRequestAnyOf4RequestFromJSON,
  WebhookPostRequestAnyOf4RequestFromJSONTyped,
  WebhookPostRequestAnyOf4RequestToJSON,
  WebhookPostRequestAnyOf4RequestToJSONTyped,
} from "./WebhookPostRequestAnyOf4Request.js";

/**
 *
 * @export
 * @interface WebhookPostRequestAnyOf4
 */
export interface WebhookPostRequestAnyOf4 {
  /**
   *
   * @type {string}
   * @memberof WebhookPostRequestAnyOf4
   */
  type: WebhookPostRequestAnyOf4TypeEnum;
  /**
   *
   * @type {string}
   * @memberof WebhookPostRequestAnyOf4
   */
  userId: string;
  /**
   *
   * @type {string}
   * @memberof WebhookPostRequestAnyOf4
   */
  orgId: string;
  /**
   *
   * @type {string}
   * @memberof WebhookPostRequestAnyOf4
   */
  timestamp: string;
  /**
   *
   * @type {string}
   * @memberof WebhookPostRequestAnyOf4
   */
  executionId: string;
  /**
   *
   * @type {WebhookPostRequestAnyOf4Request}
   * @memberof WebhookPostRequestAnyOf4
   */
  request: WebhookPostRequestAnyOf4Request;
}

/**
 * @export
 */
export const WebhookPostRequestAnyOf4TypeEnum = {
  Requesthumanfeedback: "requesthumanfeedback",
} as const;
export type WebhookPostRequestAnyOf4TypeEnum =
  (typeof WebhookPostRequestAnyOf4TypeEnum)[keyof typeof WebhookPostRequestAnyOf4TypeEnum];

/**
 * Check if a given object implements the WebhookPostRequestAnyOf4 interface.
 */
export function instanceOfWebhookPostRequestAnyOf4(
  value: object,
): value is WebhookPostRequestAnyOf4 {
  if (!("type" in value) || value["type"] === undefined) return false;
  if (!("userId" in value) || value["userId"] === undefined) return false;
  if (!("orgId" in value) || value["orgId"] === undefined) return false;
  if (!("timestamp" in value) || value["timestamp"] === undefined) return false;
  if (!("executionId" in value) || value["executionId"] === undefined)
    return false;
  if (!("request" in value) || value["request"] === undefined) return false;
  return true;
}

export function WebhookPostRequestAnyOf4FromJSON(
  json: any,
): WebhookPostRequestAnyOf4 {
  return WebhookPostRequestAnyOf4FromJSONTyped(json, false);
}

export function WebhookPostRequestAnyOf4FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): WebhookPostRequestAnyOf4 {
  if (json == null) {
    return json;
  }
  return {
    type: json["type"],
    userId: json["userId"],
    orgId: json["orgId"],
    timestamp: json["timestamp"],
    executionId: json["executionId"],
    request: WebhookPostRequestAnyOf4RequestFromJSON(json["request"]),
  };
}

export function WebhookPostRequestAnyOf4ToJSON(
  json: any,
): WebhookPostRequestAnyOf4 {
  return WebhookPostRequestAnyOf4ToJSONTyped(json, false);
}

export function WebhookPostRequestAnyOf4ToJSONTyped(
  value?: WebhookPostRequestAnyOf4 | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    type: value["type"],
    userId: value["userId"],
    orgId: value["orgId"],
    timestamp: value["timestamp"],
    executionId: value["executionId"],
    request: WebhookPostRequestAnyOf4RequestToJSON(value["request"]),
  };
}
