/* tslint:disable */
/* eslint-disable */
/**
 * Agent-Core API
 * Agent-Core Service - Control plane for multi-agent workflow orchestration
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.js";
/**
 *
 * @export
 * @interface WebhookPostRequestAnyOf4RequestAnyOf1
 */
export interface WebhookPostRequestAnyOf4RequestAnyOf1 {
  /**
   *
   * @type {string}
   * @memberof WebhookPostRequestAnyOf4RequestAnyOf1
   */
  type: WebhookPostRequestAnyOf4RequestAnyOf1TypeEnum;
  /**
   *
   * @type {Array<string>}
   * @memberof WebhookPostRequestAnyOf4RequestAnyOf1
   */
  options: Array<string>;
}

/**
 * @export
 */
export const WebhookPostRequestAnyOf4RequestAnyOf1TypeEnum = {
  Options: "options",
} as const;
export type WebhookPostRequestAnyOf4RequestAnyOf1TypeEnum =
  (typeof WebhookPostRequestAnyOf4RequestAnyOf1TypeEnum)[keyof typeof WebhookPostRequestAnyOf4RequestAnyOf1TypeEnum];

/**
 * Check if a given object implements the WebhookPostRequestAnyOf4RequestAnyOf1 interface.
 */
export function instanceOfWebhookPostRequestAnyOf4RequestAnyOf1(
  value: object,
): value is WebhookPostRequestAnyOf4RequestAnyOf1 {
  if (!("type" in value) || value["type"] === undefined) return false;
  if (!("options" in value) || value["options"] === undefined) return false;
  return true;
}

export function WebhookPostRequestAnyOf4RequestAnyOf1FromJSON(
  json: any,
): WebhookPostRequestAnyOf4RequestAnyOf1 {
  return WebhookPostRequestAnyOf4RequestAnyOf1FromJSONTyped(json, false);
}

export function WebhookPostRequestAnyOf4RequestAnyOf1FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): WebhookPostRequestAnyOf4RequestAnyOf1 {
  if (json == null) {
    return json;
  }
  return {
    type: json["type"],
    options: json["options"],
  };
}

export function WebhookPostRequestAnyOf4RequestAnyOf1ToJSON(
  json: any,
): WebhookPostRequestAnyOf4RequestAnyOf1 {
  return WebhookPostRequestAnyOf4RequestAnyOf1ToJSONTyped(json, false);
}

export function WebhookPostRequestAnyOf4RequestAnyOf1ToJSONTyped(
  value?: WebhookPostRequestAnyOf4RequestAnyOf1 | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    type: value["type"],
    options: value["options"],
  };
}
