/* tslint:disable */
/* eslint-disable */
/**
 * Agent-Core API
 * Agent-Core Service - Control plane for multi-agent workflow orchestration
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhookPostRequestAnyOf9
 */
export interface WebhookPostRequestAnyOf9 {
    /**
     * 
     * @type {string}
     * @memberof WebhookPostRequestAnyOf9
     */
    type: WebhookPostRequestAnyOf9TypeEnum;
    /**
     * 
     * @type {string}
     * @memberof WebhookPostRequestAnyOf9
     */
    agentId: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookPostRequestAnyOf9
     */
    orgId: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookPostRequestAnyOf9
     */
    executionId: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookPostRequestAnyOf9
     */
    timestamp: string;
}


/**
 * @export
 */
export const WebhookPostRequestAnyOf9TypeEnum = {
    Runintent: 'runintent'
} as const;
export type WebhookPostRequestAnyOf9TypeEnum = typeof WebhookPostRequestAnyOf9TypeEnum[keyof typeof WebhookPostRequestAnyOf9TypeEnum];


/**
 * Check if a given object implements the WebhookPostRequestAnyOf9 interface.
 */
export function instanceOfWebhookPostRequestAnyOf9(value: object): value is WebhookPostRequestAnyOf9 {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('agentId' in value) || value['agentId'] === undefined) return false;
    if (!('orgId' in value) || value['orgId'] === undefined) return false;
    if (!('executionId' in value) || value['executionId'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function WebhookPostRequestAnyOf9FromJSON(json: any): WebhookPostRequestAnyOf9 {
    return WebhookPostRequestAnyOf9FromJSONTyped(json, false);
}

export function WebhookPostRequestAnyOf9FromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookPostRequestAnyOf9 {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'agentId': json['agentId'],
        'orgId': json['orgId'],
        'executionId': json['executionId'],
        'timestamp': json['timestamp'],
    };
}

export function WebhookPostRequestAnyOf9ToJSON(json: any): WebhookPostRequestAnyOf9 {
    return WebhookPostRequestAnyOf9ToJSONTyped(json, false);
}

export function WebhookPostRequestAnyOf9ToJSONTyped(value?: WebhookPostRequestAnyOf9 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'agentId': value['agentId'],
        'orgId': value['orgId'],
        'executionId': value['executionId'],
        'timestamp': value['timestamp'],
    };
}

