/* tslint:disable */
/* eslint-disable */
/**
 * ConnectHub API
 * Unified integration, token, and proxy layer for Clancy Digital-Employees
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  ConnectionsGet200Response,
  ConnectionsIdPatch200Response,
  ConnectionsIdPatchRequest,
  ErrorResponse,
} from '../models/index.js';
import {
    ConnectionsGet200ResponseFromJSON,
    ConnectionsGet200ResponseToJSON,
    ConnectionsIdPatch200ResponseFromJSON,
    ConnectionsIdPatch200ResponseToJSON,
    ConnectionsIdPatchRequestFromJSON,
    ConnectionsIdPatchRequestToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/index.js';

export interface ConnectionsIdPatchOperationRequest {
    id: string;
    connectionsIdPatchRequest?: ConnectionsIdPatchRequest;
}

/**
 * 
 */
export class ConnectionApi extends runtime.BaseAPI {

    /**
     * Get all connections
     */
    async connectionsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConnectionsGet200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/connections`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConnectionsGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Get all connections
     */
    async connectionsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConnectionsGet200Response> {
        const response = await this.connectionsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Update connection status
     */
    async connectionsIdPatchRaw(requestParameters: ConnectionsIdPatchOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConnectionsIdPatch200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling connectionsIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/connections/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: ConnectionsIdPatchRequestToJSON(requestParameters['connectionsIdPatchRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConnectionsIdPatch200ResponseFromJSON(jsonValue));
    }

    /**
     * Update connection status
     */
    async connectionsIdPatch(requestParameters: ConnectionsIdPatchOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConnectionsIdPatch200Response> {
        const response = await this.connectionsIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
