/* tslint:disable */
/* eslint-disable */
/**
 * ConnectHub API
 * Unified integration, token, and proxy layer for Clancy Digital-Employees
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  ErrorResponse,
  ProxyProviderIdCapabilityIdPostRequest,
} from '../models/index.js';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ProxyProviderIdCapabilityIdPostRequestFromJSON,
    ProxyProviderIdCapabilityIdPostRequestToJSON,
} from '../models/index.js';

export interface ProxyProviderIdCapabilityIdPostOperationRequest {
    providerId: string;
    capabilityId: string;
    proxyProviderIdCapabilityIdPostRequest: ProxyProviderIdCapabilityIdPostRequest;
}

/**
 * 
 */
export class ProxyApi extends runtime.BaseAPI {

    /**
     * Proxies action requests
     */
    async proxyProviderIdCapabilityIdPostRaw(requestParameters: ProxyProviderIdCapabilityIdPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['providerId'] == null) {
            throw new runtime.RequiredError(
                'providerId',
                'Required parameter "providerId" was null or undefined when calling proxyProviderIdCapabilityIdPost().'
            );
        }

        if (requestParameters['capabilityId'] == null) {
            throw new runtime.RequiredError(
                'capabilityId',
                'Required parameter "capabilityId" was null or undefined when calling proxyProviderIdCapabilityIdPost().'
            );
        }

        if (requestParameters['proxyProviderIdCapabilityIdPostRequest'] == null) {
            throw new runtime.RequiredError(
                'proxyProviderIdCapabilityIdPostRequest',
                'Required parameter "proxyProviderIdCapabilityIdPostRequest" was null or undefined when calling proxyProviderIdCapabilityIdPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/proxy/{providerId}/{capabilityId}`.replace(`{${"providerId"}}`, encodeURIComponent(String(requestParameters['providerId']))).replace(`{${"capabilityId"}}`, encodeURIComponent(String(requestParameters['capabilityId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ProxyProviderIdCapabilityIdPostRequestToJSON(requestParameters['proxyProviderIdCapabilityIdPostRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Proxies action requests
     */
    async proxyProviderIdCapabilityIdPost(requestParameters: ProxyProviderIdCapabilityIdPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.proxyProviderIdCapabilityIdPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
