/* tslint:disable */
/* eslint-disable */
/**
 * ConnectHub API
 * Unified integration, token, and proxy layer for Clancy Digital-Employees
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Trigger,
  TriggerRegistration,
} from '../models/index';
import {
    TriggerFromJSON,
    TriggerToJSON,
    TriggerRegistrationFromJSON,
    TriggerRegistrationToJSON,
} from '../models/index';

export interface TriggerRegistrationsPostRequest {
    triggerRegistration?: Omit<TriggerRegistration, 'id'|'createdAt'|'updatedAt'>;
}

/**
 * 
 */
export class TriggersApi extends runtime.BaseAPI {

    /**
     */
    async triggerRegistrationsPostRaw(requestParameters: TriggerRegistrationsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TriggerRegistration>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/trigger-registrations`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TriggerRegistrationToJSON(requestParameters['triggerRegistration']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TriggerRegistrationFromJSON(jsonValue));
    }

    /**
     */
    async triggerRegistrationsPost(requestParameters: TriggerRegistrationsPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TriggerRegistration> {
        const response = await this.triggerRegistrationsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async triggersGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Trigger>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/triggers`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TriggerFromJSON));
    }

    /**
     */
    async triggersGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Trigger>> {
        const response = await this.triggersGetRaw(initOverrides);
        return await response.value();
    }

}
