/* tslint:disable */
/* eslint-disable */
/**
 * ConnectHub API
 * Unified integration, token, and proxy layer for Clancy Digital-Employees
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  WebhooksInternalPostRequest,
  WebhooksSlackPostRequest,
} from '../models/index';
import {
    WebhooksInternalPostRequestFromJSON,
    WebhooksInternalPostRequestToJSON,
    WebhooksSlackPostRequestFromJSON,
    WebhooksSlackPostRequestToJSON,
} from '../models/index';

export interface WebhooksInternalPostOperationRequest {
    webhooksInternalPostRequest?: WebhooksInternalPostRequest;
}

export interface WebhooksSlackPostOperationRequest {
    webhooksSlackPostRequest?: WebhooksSlackPostRequest;
}

/**
 * 
 */
export class WebhooksApi extends runtime.BaseAPI {

    /**
     * Internal webhook
     */
    async webhooksInternalPostRaw(requestParameters: WebhooksInternalPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/webhooks/internal`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WebhooksInternalPostRequestToJSON(requestParameters['webhooksInternalPostRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Internal webhook
     */
    async webhooksInternalPost(requestParameters: WebhooksInternalPostOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.webhooksInternalPostRaw(requestParameters, initOverrides);
    }

    /**
     * Slack Events API callback
     */
    async webhooksSlackPostRaw(requestParameters: WebhooksSlackPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/webhooks/slack`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WebhooksSlackPostRequestToJSON(requestParameters['webhooksSlackPostRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Slack Events API callback
     */
    async webhooksSlackPost(requestParameters: WebhooksSlackPostOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.webhooksSlackPostRaw(requestParameters, initOverrides);
    }

}
