/* tslint:disable */
/* eslint-disable */
/**
 * Agent-Core API
 * Agent-Core Service - Control plane for multi-agent workflow orchestration
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  PublicTemplatesGet200ResponseInner,
  V1AgentsPost400Response,
} from '../models/index.js';
import {
    PublicTemplatesGet200ResponseInnerFromJSON,
    PublicTemplatesGet200ResponseInnerToJSON,
    V1AgentsPost400ResponseFromJSON,
    V1AgentsPost400ResponseToJSON,
} from '../models/index.js';

export interface PublicTemplatesIdGetRequest {
    id: string;
}

/**
 * 
 */
export class TemplatesApi extends runtime.BaseAPI {

    /**
     * List templates for landing page and library
     * List public templates
     */
    async publicTemplatesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PublicTemplatesGet200ResponseInner>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/public/templates`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PublicTemplatesGet200ResponseInnerFromJSON));
    }

    /**
     * List templates for landing page and library
     * List public templates
     */
    async publicTemplatesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PublicTemplatesGet200ResponseInner>> {
        const response = await this.publicTemplatesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get a template by id
     * Get a public template
     */
    async publicTemplatesIdGetRaw(requestParameters: PublicTemplatesIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublicTemplatesGet200ResponseInner>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling publicTemplatesIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/public/templates/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PublicTemplatesGet200ResponseInnerFromJSON(jsonValue));
    }

    /**
     * Get a template by id
     * Get a public template
     */
    async publicTemplatesIdGet(requestParameters: PublicTemplatesIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublicTemplatesGet200ResponseInner> {
        const response = await this.publicTemplatesIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
